/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Error
 */
interface Error {
  /** Error code defined by FDX API Specification or Data Provider indicating the error situation which has occurred */
  code?: number;
  /** End user displayable information which might help the customer diagnose an error */
  message?: string;
  /** Message used to debug the root cause of the error. Contents should not be used in consumer's business logic. Can change at any time and should only be used for consumer to communicate with the data provider about an issue. Provider can include an error GUID in message for their use. */
  debugMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ErrorError extends ApiError<Error> {}
