/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import {
  AnnuityAccountInfo,
  annuityAccountInfoSchema,
} from '../annuityAccountInfo';
import {
  DepositAccountInfo,
  depositAccountInfoSchema,
} from '../depositAccountInfo';
import {
  InsuranceAccountInfo,
  insuranceAccountInfoSchema,
} from '../insuranceAccountInfo';
import {
  InvestmentAccountInfo,
  investmentAccountInfoSchema,
} from '../investmentAccountInfo';
import { LoanAccountInfo, loanAccountInfoSchema } from '../loanAccountInfo';
import { LocAccountInfo, locAccountInfoSchema } from '../locAccountInfo';

/** This is a container type for any-of types. */
export type AkoyaAccountInfoProductAccounts =
  | DepositAccountInfo
  | LoanAccountInfo
  | LocAccountInfo
  | InvestmentAccountInfo
  | InsuranceAccountInfo
  | AnnuityAccountInfo;

export const akoyaAccountInfoProductAccountsSchema: Schema<AkoyaAccountInfoProductAccounts> = anyOf(
  [
    depositAccountInfoSchema,
    loanAccountInfoSchema,
    locAccountInfoSchema,
    investmentAccountInfoSchema,
    insuranceAccountInfoSchema,
    annuityAccountInfoSchema,
  ]
);

export namespace AkoyaAccountInfoProductAccounts {
  /**
   * Validation method to narrow down union type to DepositAccountInfo type case.
   *
   * This is DepositAccountInfo case.
   */
  export function isDepositAccountInfo(
    value: unknown
  ): value is DepositAccountInfo {
    const validationResult = validateAndMap(value, depositAccountInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LoanAccountInfo type case.
   *
   * This is LoanAccountInfo case.
   */
  export function isLoanAccountInfo(value: unknown): value is LoanAccountInfo {
    const validationResult = validateAndMap(value, loanAccountInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LocAccountInfo type case.
   *
   * This is LocAccountInfo case.
   */
  export function isLocAccountInfo(value: unknown): value is LocAccountInfo {
    const validationResult = validateAndMap(value, locAccountInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InvestmentAccountInfo type case.
   *
   * This is InvestmentAccountInfo case.
   */
  export function isInvestmentAccountInfo(
    value: unknown
  ): value is InvestmentAccountInfo {
    const validationResult = validateAndMap(value, investmentAccountInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InsuranceAccountInfo type case.
   *
   * This is InsuranceAccountInfo case.
   */
  export function isInsuranceAccountInfo(
    value: unknown
  ): value is InsuranceAccountInfo {
    const validationResult = validateAndMap(value, insuranceAccountInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to AnnuityAccountInfo type case.
   *
   * This is AnnuityAccountInfo case.
   */
  export function isAnnuityAccountInfo(
    value: unknown
  ): value is AnnuityAccountInfo {
    const validationResult = validateAndMap(value, annuityAccountInfoSchema);
    return validationResult.errors === false;
  }
}
