/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { AnnuityBalance, annuityBalanceSchema } from '../annuityBalance';
import { DepositBalance, depositBalanceSchema } from '../depositBalance';
import { InsuranceBalance, insuranceBalanceSchema } from '../insuranceBalance';
import {
  InvestmentBalance,
  investmentBalanceSchema,
} from '../investmentBalance';
import { LoanBalance, loanBalanceSchema } from '../loanBalance';
import { LocBalance, locBalanceSchema } from '../locBalance';

/** This is a container type for any-of types. */
export type BalancesAccounts =
  | DepositBalance
  | LoanBalance
  | LocBalance
  | InvestmentBalance
  | InsuranceBalance
  | AnnuityBalance;

export const balancesAccountsSchema: Schema<BalancesAccounts> = anyOf([
  depositBalanceSchema,
  loanBalanceSchema,
  locBalanceSchema,
  investmentBalanceSchema,
  insuranceBalanceSchema,
  annuityBalanceSchema,
]);

export namespace BalancesAccounts {
  /**
   * Validation method to narrow down union type to DepositBalance type case.
   *
   * This is DepositBalance case.
   */
  export function isDepositBalance(value: unknown): value is DepositBalance {
    const validationResult = validateAndMap(value, depositBalanceSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LoanBalance type case.
   *
   * This is LoanBalance case.
   */
  export function isLoanBalance(value: unknown): value is LoanBalance {
    const validationResult = validateAndMap(value, loanBalanceSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LocBalance type case.
   *
   * This is LocBalance case.
   */
  export function isLocBalance(value: unknown): value is LocBalance {
    const validationResult = validateAndMap(value, locBalanceSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InvestmentBalance type case.
   *
   * This is InvestmentBalance case.
   */
  export function isInvestmentBalance(
    value: unknown
  ): value is InvestmentBalance {
    const validationResult = validateAndMap(value, investmentBalanceSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InsuranceBalance type case.
   *
   * This is InsuranceBalance case.
   */
  export function isInsuranceBalance(
    value: unknown
  ): value is InsuranceBalance {
    const validationResult = validateAndMap(value, insuranceBalanceSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to AnnuityBalance type case.
   *
   * This is AnnuityBalance case.
   */
  export function isAnnuityBalance(value: unknown): value is AnnuityBalance {
    const validationResult = validateAndMap(value, annuityBalanceSchema);
    return validationResult.errors === false;
  }
}
