/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import {
  DepositTransactionInfo,
  depositTransactionInfoSchema,
} from '../depositTransactionInfo';
import {
  InsuranceTransactionInfo,
  insuranceTransactionInfoSchema,
} from '../insuranceTransactionInfo';
import {
  InvestmentTransactionInfo,
  investmentTransactionInfoSchema,
} from '../investmentTransactionInfo';
import {
  LoanTransactionInfo,
  loanTransactionInfoSchema,
} from '../loanTransactionInfo';
import {
  LocTransactionInfo,
  locTransactionInfoSchema,
} from '../locTransactionInfo';

/** This is a container type for any-of types. */
export type TransactionsEntityTransactions =
  | DepositTransactionInfo
  | LoanTransactionInfo
  | LocTransactionInfo
  | InvestmentTransactionInfo
  | InsuranceTransactionInfo;

export const transactionsEntityTransactionsSchema: Schema<TransactionsEntityTransactions> = anyOf(
  [
    depositTransactionInfoSchema,
    loanTransactionInfoSchema,
    locTransactionInfoSchema,
    investmentTransactionInfoSchema,
    insuranceTransactionInfoSchema,
  ]
);

export namespace TransactionsEntityTransactions {
  /**
   * Validation method to narrow down union type to DepositTransactionInfo type case.
   *
   * This is DepositTransactionInfo case.
   */
  export function isDepositTransactionInfo(
    value: unknown
  ): value is DepositTransactionInfo {
    const validationResult = validateAndMap(
      value,
      depositTransactionInfoSchema
    );
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LoanTransactionInfo type case.
   *
   * This is LoanTransactionInfo case.
   */
  export function isLoanTransactionInfo(
    value: unknown
  ): value is LoanTransactionInfo {
    const validationResult = validateAndMap(value, loanTransactionInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to LocTransactionInfo type case.
   *
   * This is LocTransactionInfo case.
   */
  export function isLocTransactionInfo(
    value: unknown
  ): value is LocTransactionInfo {
    const validationResult = validateAndMap(value, locTransactionInfoSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InvestmentTransactionInfo type case.
   *
   * This is InvestmentTransactionInfo case.
   */
  export function isInvestmentTransactionInfo(
    value: unknown
  ): value is InvestmentTransactionInfo {
    const validationResult = validateAndMap(
      value,
      investmentTransactionInfoSchema
    );
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to InsuranceTransactionInfo type case.
   *
   * This is InsuranceTransactionInfo case.
   */
  export function isInsuranceTransactionInfo(
    value: unknown
  ): value is InsuranceTransactionInfo {
    const validationResult = validateAndMap(
      value,
      insuranceTransactionInfoSchema
    );
    return validationResult.errors === false;
  }
}
