/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept
 */
export enum Accept {
  EnumApplicationpdf = 'application/pdf',
  EnumImagegif = 'image/gif',
  EnumImagejpeg = 'image/jpeg',
  EnumImagetiff = 'image/tiff',
  EnumImagepng = 'image/png',
}

/**
 * Schema for Accept
 */
export const acceptSchema: Schema<Accept> = stringEnum(Accept, true);
