/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountHolderRelationship
 */
export enum AccountHolderRelationship {
  AuthorizedUser = 'AUTHORIZED_USER',
  Business = 'BUSINESS',
  ForBenefitOf = 'FOR_BENEFIT_OF',
  ForBenefitOfPrimary = 'FOR_BENEFIT_OF_PRIMARY',
  ForBenefitOfPrimaryJointRestricted = 'FOR_BENEFIT_OF_PRIMARY_JOINT_RESTRICTED',
  ForBenefitOfSecondary = 'FOR_BENEFIT_OF_SECONDARY',
  ForBenefitOfSecondaryJointRestricted = 'FOR_BENEFIT_OF_SECONDARY_JOINT_RESTRICTED',
  ForBenefitOfSoleOwnerRestricted = 'FOR_BENEFIT_OF_SOLE_OWNER_RESTRICTED',
  PowerOfAttorney = 'POWER_OF_ATTORNEY',
  PrimaryJointTenants = 'PRIMARY_JOINT_TENANTS',
  Primary = 'PRIMARY',
  PrimaryBorrower = 'PRIMARY_BORROWER',
  PrimaryJoint = 'PRIMARY_JOINT',
  Secondary = 'SECONDARY',
  SecondaryJointTenants = 'SECONDARY_JOINT_TENANTS',
  SecondaryBorrower = 'SECONDARY_BORROWER',
  SecondaryJoint = 'SECONDARY_JOINT',
  SoleOwner = 'SOLE_OWNER',
  Trustee = 'TRUSTEE',
  UniformTransferToMinor = 'UNIFORM_TRANSFER_TO_MINOR',
}

/**
 * Schema for AccountHolderRelationship
 */
export const accountHolderRelationshipSchema: Schema<AccountHolderRelationship> = stringEnum(
  AccountHolderRelationship,
  true
);
