/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  AccountHolderEntityRelationship,
  accountHolderEntityRelationshipSchema,
} from './accountHolderEntityRelationship';
import { AddressInfo, addressInfoSchema } from './addressInfo';
import { Name, nameSchema } from './name';

/** Extends `Customer` and adds a `relationship` field to define the customer's relationship with an account */
export interface AccountHolderEntity {
  /** Long-term persistent identity of the end-user. This identity must be unique to the owning institution */
  customerId?: string;
  /** The end-user's name */
  name?: Name;
  /** An array of the end-user's physical mail addresses */
  addresses?: AddressInfo[];
  /** Optional array of telephone numbers */
  telephones?: string[] | null;
  /** An array of the end-user's electronic mail addresses */
  email?: string[];
  /** Optional list of accounts associated with the customer */
  accounts?: string[] | null;
  /** Customer's relationship to the account */
  relationship?: AccountHolderEntityRelationship;
  additionalProperties?: Record<string, unknown>;
}

export const accountHolderEntitySchema: Schema<AccountHolderEntity> = typedExpandoObject(
  {
    customerId: ['customerId', optional(string())],
    name: ['name', optional(lazy(() => nameSchema))],
    addresses: ['addresses', optional(array(lazy(() => addressInfoSchema)))],
    telephones: ['telephones', optional(nullable(array(string())))],
    email: ['email', optional(array(string()))],
    accounts: ['accounts', optional(nullable(array(string())))],
    relationship: [
      'relationship',
      optional(accountHolderEntityRelationshipSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
