/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountHolderEntityRelationship
 */
export enum AccountHolderEntityRelationship {
  Primary = 'PRIMARY',
  Joint = 'JOINT',
  AuthorizedUser = 'AUTHORIZED_USER',
}

/**
 * Schema for AccountHolderEntityRelationship
 */
export const accountHolderEntityRelationshipSchema: Schema<AccountHolderEntityRelationship> = stringEnum(
  AccountHolderEntityRelationship,
  true
);
