/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  AccountHolderEntity,
  accountHolderEntitySchema,
} from './accountHolderEntity';
import { DeliveryAddress, deliveryAddressSchema } from './deliveryAddress';
import { TelephoneNumber, telephoneNumberSchema } from './telephoneNumber';

/** Contact information for the account */
export interface AccountContactEntity {
  /** Owners of the account */
  holders?: AccountHolderEntity[];
  /** Email addresses associated with the account */
  emails?: string[];
  addresses?: DeliveryAddress[];
  /** Telephone numbers associated with the account. */
  telephones?: TelephoneNumber[];
  additionalProperties?: Record<string, unknown>;
}

export const accountContactEntitySchema: Schema<AccountContactEntity> = typedExpandoObject(
  {
    holders: [
      'holders',
      optional(array(lazy(() => accountHolderEntitySchema))),
    ],
    emails: ['emails', optional(array(string()))],
    addresses: [
      'addresses',
      optional(array(lazy(() => deliveryAddressSchema))),
    ],
    telephones: [
      'telephones',
      optional(array(lazy(() => telephoneNumberSchema))),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
