/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountCategory
 */
export enum AccountCategory {
  DepositAccount = 'DEPOSIT_ACCOUNT',
  InvestmentAccount = 'INVESTMENT_ACCOUNT',
  LoanAccount = 'LOAN_ACCOUNT',
  LocAccount = 'LOC_ACCOUNT',
  InsuranceAccount = 'INSURANCE_ACCOUNT',
}

/**
 * Schema for AccountCategory
 */
export const accountCategorySchema: Schema<AccountCategory> = stringEnum(
  AccountCategory,
  true
);
