/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountInfoStatus
 */
export enum AccountInfoStatus {
  Open = 'OPEN',
  Closed = 'CLOSED',
  Pendingopen = 'PENDINGOPEN',
  Pendingclose = 'PENDINGCLOSE',
  Delinquent = 'DELINQUENT',
  Paid = 'PAID',
  Negativecurrentbalance = 'NEGATIVECURRENTBALANCE',
}

/**
 * Schema for AccountInfoStatus
 */
export const accountInfoStatusSchema: Schema<AccountInfoStatus> = stringEnum(
  AccountInfoStatus,
  true
);
