/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface AddressInfo {
  /** May contain full address if not separated */
  line1?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const addressInfoSchema: Schema<AddressInfo> = typedExpandoObject(
  {
    line1: ['line1', optional(string())],
    city: ['city', optional(string())],
    state: ['state', optional(string())],
    postalCode: ['postalCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
