/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnualIncreaseType
 */
export enum AnnualIncreaseType {
  Fixed = 'FIXED',
  Percent = 'PERCENT',
  Dollar = 'DOLLAR',
}

/**
 * Schema for AnnualIncreaseType
 */
export const annualIncreaseTypeSchema: Schema<AnnualIncreaseType> = stringEnum(
  AnnualIncreaseType,
  true
);
