/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnunityProductType
 */
export enum AnnunityProductType {
  Currency = 'CURRENCY',
  Shares = 'SHARES',
}

/**
 * Schema for AnnunityProductType
 */
export const annunityProductTypeSchema: Schema<AnnunityProductType> = stringEnum(
  AnnunityProductType,
  true
);
