/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { AnnuityAccount, annuityAccountSchema } from './annuityAccount';

export interface AnnuityAccountInfo {
  /** Annuity Account */
  annuityAccount?: AnnuityAccount;
  additionalProperties?: Record<string, unknown>;
}

export const annuityAccountInfoSchema: Schema<AnnuityAccountInfo> = typedExpandoObject(
  {
    annuityAccount: [
      'annuityAccount',
      optional(lazy(() => annuityAccountSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
