/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnuityAccountPaymentFrequency
 */
export enum AnnuityAccountPaymentFrequency {
  Annually = 'ANNUALLY',
  Quarterly = 'QUARTERLY',
  Monthly = 'MONTHLY',
  Weekly = 'WEEKLY',
}

/**
 * Schema for AnnuityAccountPaymentFrequency
 */
export const annuityAccountPaymentFrequencySchema: Schema<AnnuityAccountPaymentFrequency> = stringEnum(
  AnnuityAccountPaymentFrequency,
  true
);
