/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { AnnuityBalances, annuityBalancesSchema } from './annuityBalances';

export interface AnnuityBalance {
  /** Data elements included with balances specific to annuity accounts */
  annuityAccount?: AnnuityBalances;
  additionalProperties?: Record<string, unknown>;
}

export const annuityBalanceSchema: Schema<AnnuityBalance> = typedExpandoObject(
  {
    annuityAccount: [
      'annuityAccount',
      optional(lazy(() => annuityBalancesSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
