/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnunityValueBasis
 */
export enum AnnunityValueBasis {
  Fixed = 'FIXED',
  Variable = 'VARIABLE',
}

/**
 * Schema for AnnunityValueBasis
 */
export const annunityValueBasisSchema: Schema<AnnunityValueBasis> = stringEnum(
  AnnunityValueBasis,
  true
);
