/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  PaymentNetworkSupportedByAccount,
  paymentNetworkSupportedByAccountSchema,
} from './paymentNetworkSupportedByAccount';

/** An optionally paginated array of payment networks supported by the account */
export interface ArrayOfAccountPaymentNetworks {
  /** Array of payment networks */
  paymentNetworks?: PaymentNetworkSupportedByAccount[];
  additionalProperties?: Record<string, unknown>;
}

export const arrayOfAccountPaymentNetworksSchema: Schema<ArrayOfAccountPaymentNetworks> = typedExpandoObject(
  {
    paymentNetworks: [
      'paymentNetworks',
      optional(array(lazy(() => paymentNetworkSupportedByAccountSchema))),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
