/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { AssetClass, assetClassSchema } from './assetClass';

export interface AssetClassItem {
  assetClass?: AssetClass;
  /** Percentage of asset class that falls under this asset */
  percent?: number;
  additionalProperties?: Record<string, unknown>;
}

export const assetClassItemSchema: Schema<AssetClassItem> = typedExpandoObject(
  {
    assetClass: ['assetClass', optional(assetClassSchema)],
    percent: ['percent', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
