/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BalanceType
 */
export enum BalanceType {
  Asset = 'ASSET',
  Liability = 'LIABILITY',
}

/**
 * Schema for BalanceType
 */
export const balanceTypeSchema: Schema<BalanceType> = stringEnum(
  BalanceType,
  true
);
