/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  BalancesAccounts,
  balancesAccountsSchema,
} from './containers/balancesAccounts';

export interface Balances {
  /** An array of accounts with entity types dependent on the account type (deposit, investment, loan, line of credit, annuity or insurance) */
  accounts?: BalancesAccounts[];
  additionalProperties?: Record<string, unknown>;
}

export const balancesSchema: Schema<Balances> = typedExpandoObject(
  { accounts: ['accounts', optional(array(balancesAccountsSchema))] },
  'additionalProperties',
  optional(unknown())
);
