/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { CustomerName, customerNameSchema } from './customerName';
import { Domicile, domicileSchema } from './domicile';
import { IndustryCode, industryCodeSchema } from './industryCode';

/** Customers that are commercial in nature are affiliated with a business entity */
export interface BusinessCustomerEntity {
  /** Name of business customer */
  name?: string;
  /** A list of registered agents who act on behalf of the business customer */
  registeredAgents?: CustomerName[];
  /** The registered tax identification number (TIN) or other identifier of business customer */
  registeredId?: string;
  /** Industry code and type */
  industryCode?: IndustryCode;
  /** The country and region of the business customer's location */
  domicile?: Domicile;
  additionalProperties?: Record<string, unknown>;
}

export const businessCustomerEntitySchema: Schema<BusinessCustomerEntity> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    registeredAgents: [
      'registeredAgents',
      optional(array(lazy(() => customerNameSchema))),
    ],
    registeredId: ['registeredId', optional(string())],
    industryCode: ['industryCode', optional(lazy(() => industryCodeSchema))],
    domicile: ['domicile', optional(lazy(() => domicileSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
