/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Business issuer or recipient name */
export interface BusinessName {
  /** Name line 1 */
  name1?: string;
  /** Name line 2 */
  name2?: string;
  additionalProperties?: Record<string, unknown>;
}

export const businessNameSchema: Schema<BusinessName> = typedExpandoObject(
  {
    name1: ['name1', optional(string())],
    name2: ['name2', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
