/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallType
 */
export enum CallType {
  Call = 'CALL',
  Put = 'PUT',
  Prefund = 'PREFUND',
  Maturity = 'MATURITY',
}

/**
 * Schema for CallType
 */
export const callTypeSchema: Schema<CallType> = stringEnum(CallType, true);
