/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Code and amount pair used on IRS W-2, K-1, etc. */
export interface CodeAndAmount {
  /** Code */
  code?: string;
  /** Amount */
  amount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const codeAndAmountSchema: Schema<CodeAndAmount> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    amount: ['amount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
