/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CompoundingPeriod
 */
export enum CompoundingPeriod {
  Daily = 'DAILY',
  Weekly = 'WEEKLY',
  Biweekly = 'BIWEEKLY',
  Semimonthly = 'SEMIMONTHLY',
  Monthly = 'MONTHLY',
  Semiannually = 'SEMIANNUALLY',
  Annually = 'ANNUALLY',
}

/**
 * Schema for CompoundingPeriod
 */
export const compoundingPeriodSchema: Schema<CompoundingPeriod> = stringEnum(
  CompoundingPeriod,
  true
);
