/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ContentType
 */
export enum ContentType {
  EnumApplicationpdf = 'application/pdf',
  EnumImagegif = 'image/gif',
  EnumImagejpeg = 'image/jpeg',
  EnumImagetiff = 'image/tiff',
  EnumImagepng = 'image/png',
  EnumApplicationjson = 'application/json',
}

/**
 * Schema for ContentType
 */
export const contentTypeSchema: Schema<ContentType> = stringEnum(
  ContentType,
  true
);
