/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { SecurityIdType, securityIdTypeSchema } from './securityIdType';

/** Describes how new contributions are distributed among the available securities. */
export interface ContributionEntity {
  /** Unique identifier of security */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdType;
  /** Employer contribution match percentage */
  employerMatchPercentage?: number;
  /** Employer contribution match amount */
  employerMatchAmount?: number;
  /** Employee pre‐tax contribution amount */
  employeePreTaxAmount?: number;
  /** Employee pre‐tax contribution percentage */
  employeePreTaxPercentage?: number;
  /** Employee after tax contribution amount */
  employeeAfterTaxAmount?: number;
  /** Employee after tax contribution percentage */
  employeeAfterTaxPercentage?: number;
  /** Employee defer pre‐tax contribution match amount */
  employeeDeferPreTaxAmount?: number;
  /** Employee defer pre‐tax contribution match percentage */
  employeeDeferPreTaxPercentage?: number;
  /** Employee total year to date contribution */
  employeeYearToDate?: number;
  /** Employer total year to date contribution */
  employerYearToDate?: number;
  /** Rollover contribution percentage */
  rolloverContributionPercentage?: number;
  /** Rollover contribution Amount */
  rolloverContributionAmount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const contributionEntitySchema: Schema<ContributionEntity> = typedExpandoObject(
  {
    securityId: ['securityId', optional(string())],
    securityIdType: ['securityIdType', optional(securityIdTypeSchema)],
    employerMatchPercentage: ['employerMatchPercentage', optional(number())],
    employerMatchAmount: ['employerMatchAmount', optional(number())],
    employeePreTaxAmount: ['employeePreTaxAmount', optional(number())],
    employeePreTaxPercentage: ['employeePreTaxPercentage', optional(number())],
    employeeAfterTaxAmount: ['employeeAfterTaxAmount', optional(number())],
    employeeAfterTaxPercentage: [
      'employeeAfterTaxPercentage',
      optional(number()),
    ],
    employeeDeferPreTaxAmount: [
      'employeeDeferPreTaxAmount',
      optional(number()),
    ],
    employeeDeferPreTaxPercentage: [
      'employeeDeferPreTaxPercentage',
      optional(number()),
    ],
    employeeYearToDate: ['employeeYearToDate', optional(number())],
    employerYearToDate: ['employerYearToDate', optional(number())],
    rolloverContributionPercentage: [
      'rolloverContributionPercentage',
      optional(number()),
    ],
    rolloverContributionAmount: [
      'rolloverContributionAmount',
      optional(number()),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
