/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CouponMatureFrequency
 */
export enum CouponMatureFrequency {
  Monthly = 'MONTHLY',
  Quarterly = 'QUARTERLY',
  Semiannual = 'SEMIANNUAL',
  Annual = 'ANNUAL',
  Other = 'OTHER',
}

/**
 * Schema for CouponMatureFrequency
 */
export const couponMatureFrequencySchema: Schema<CouponMatureFrequency> = stringEnum(
  CouponMatureFrequency,
  true
);
