/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CoverageMonth
 */
export enum CoverageMonth {
  Annual = 'ANNUAL',
  January = 'JANUARY',
  February = 'FEBRUARY',
  March = 'MARCH',
  April = 'APRIL',
  May = 'MAY',
  June = 'JUNE',
  July = 'JULY',
  August = 'AUGUST',
  September = 'SEPTEMBER',
  October = 'OCTOBER',
  November = 'NOVEMBER',
  December = 'DECEMBER',
}

/**
 * Schema for CoverageMonth
 */
export const coverageMonthSchema: Schema<CoverageMonth> = stringEnum(
  CoverageMonth,
  true
);
