/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Customer, customerSchema } from './customer';

export interface CurrentCustomer {
  /** Represents a customer (end-user) */
  customer?: Customer;
  additionalProperties?: Record<string, unknown>;
}

export const currentCustomerSchema: Schema<CurrentCustomer> = typedExpandoObject(
  { customer: ['customer', optional(lazy(() => customerSchema))] },
  'additionalProperties',
  optional(unknown())
);
