/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Indicates the currency code used by the account. May also include currency rate. */
export interface CurrencyEntity {
  /** Iso 4217 currency code. */
  currencyCode?: string;
  /** Currency rate between original and converted currency. */
  currencyRate?: number;
  /** Iso 4217 currency code. */
  originalCurrencyCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const currencyEntitySchema: Schema<CurrencyEntity> = typedExpandoObject(
  {
    currencyCode: ['currencyCode', optional(string())],
    currencyRate: ['currencyRate', optional(number())],
    originalCurrencyCode: ['originalCurrencyCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
