/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { AddressInfo, addressInfoSchema } from './addressInfo';
import { Name, nameSchema } from './name';

/** Represents a customer (end-user) */
export interface Customer {
  /** Long-term persistent identity of the end-user. This identity must be unique to the owning institution */
  customerId?: string;
  /** The end-user's name */
  name?: Name;
  /** An array of the end-user's physical mail addresses */
  addresses?: AddressInfo[];
  /** Optional array of telephone numbers */
  telephones?: string[] | null;
  /** An array of the end-user's electronic mail addresses */
  email?: string[];
  /** Optional list of accounts associated with the customer */
  accounts?: string[] | null;
  additionalProperties?: Record<string, unknown>;
}

export const customerSchema: Schema<Customer> = typedExpandoObject(
  {
    customerId: ['customerId', optional(string())],
    name: ['name', optional(lazy(() => nameSchema))],
    addresses: ['addresses', optional(array(lazy(() => addressInfoSchema)))],
    telephones: ['telephones', optional(nullable(array(string())))],
    email: ['email', optional(array(string()))],
    accounts: ['accounts', optional(nullable(array(string())))],
  },
  'additionalProperties',
  optional(unknown())
);
