/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface CustomerName {
  /** First or given name. This data element may contain first & last name if not separated. */
  first?: string;
  middle?: string;
  last?: string;
  /** Name prefix, e.g. Mr. */
  prefix?: string;
  /** Generational or academic suffix */
  suffix?: string;
  /** Company name */
  company?: string;
  additionalProperties?: Record<string, unknown>;
}

export const customerNameSchema: Schema<CustomerName> = typedExpandoObject(
  {
    first: ['first', optional(string())],
    middle: ['middle', optional(string())],
    last: ['last', optional(string())],
    prefix: ['prefix', optional(string())],
    suffix: ['suffix', optional(string())],
    company: ['company', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
