/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebitCreditMemo
 */
export enum DebitCreditMemo {
  Debit = 'DEBIT',
  Credit = 'CREDIT',
}

/**
 * Schema for DebitCreditMemo
 */
export const debitCreditMemoSchema: Schema<DebitCreditMemo> = stringEnum(
  DebitCreditMemo,
  true
);
