/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebtClass
 */
export enum DebtClass {
  Treasury = 'TREASURY',
  Municipal = 'MUNICIPAL',
  Corporate = 'CORPORATE',
  Other = 'OTHER',
}

/**
 * Schema for DebtClass
 */
export const debtClassSchema: Schema<DebtClass> = stringEnum(DebtClass, true);
