/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebtType
 */
export enum DebtType {
  Asset = 'ASSET',
  Coupon = 'COUPON',
}

/**
 * Schema for DebtType
 */
export const debtTypeSchema: Schema<DebtType> = stringEnum(DebtType, true);
