/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  AccountInfoStatus,
  accountInfoStatusSchema,
} from './accountInfoStatus';
import { BalanceType, balanceTypeSchema } from './balanceType';
import { CurrencyEntity, currencyEntitySchema } from './currencyEntity';
import {
  FiAttributeEntity,
  fiAttributeEntitySchema,
} from './fiAttributeEntity';
import { InterestRateType, interestRateTypeSchema } from './interestRateType';

/** Data elements included with balances specific to deposit accounts */
export interface DepositBalances {
  /** Long-term persistent identity of the account. Not an account number. This identity must be unique to the owning institution. */
  accountId?: string;
  /** The type of an account. For instance, CHECKING, SAVINGS, 401K, etc. */
  accountType?: string;
  /** Account display number for the end user’s handle at owning institution. This is to be displayed by the Interface Provider. */
  accountNumberDisplay?: string;
  /** Indicates the currency code used by the account. May also include currency rate. */
  currency?: CurrencyEntity;
  description?: string;
  fiAttributes?: FiAttributeEntity[];
  /** Name given by the user. Used in UIs to assist in account selection */
  nickname?: string;
  /** Marketed product name for this account.  Used in UIs to assist in account selection */
  productName?: string;
  /** The status of an account. */
  status?: AccountInfoStatus;
  /** The line of business, such as consumer, consumer joint, small business, corporate, etc. */
  lineOfBusiness?: string;
  /** ASSET (positive transaction amount increases balance), LIABILITY (positive transaction amount decreases balance) */
  balanceType?: BalanceType;
  /** Interest Rate of Account */
  interestRate?: number;
  /** The type of interest rate. FIXED or VARIABLE. */
  interestRateType?: InterestRateType;
  /** Date of account’s interest rate */
  interestRateAsOf?: string;
  /** Date that last transaction occurred on account */
  lastActivityDate?: string;
  /** MICR Number */
  micrNumber?: string;
  /** Long-term persistent identity of the parent account. This is used to group accounts. */
  parentAccountId?: string;
  /** Previous Interest Rate of Account */
  priorInterestRate?: number;
  /** Account is eligible for incoming transfers */
  transferIn?: boolean;
  /** Account is eligible for outgoing transfers */
  transferOut?: boolean;
  /** Annual Percentage Yield. */
  annualPercentageYield?: number;
  /** Term of CD in months */
  term?: number;
  /** Maturity date for CDs. */
  maturityDate?: string;
  /** As-of date of balances */
  balanceAsOf?: string;
  /** Day's opening fund balance */
  openingDayBalance?: number;
  /** Balance of funds available for use */
  availableBalance?: number;
  /** YTD Interest */
  interestYtd?: number;
  /** Balance of funds in account */
  currentBalance?: number;
  additionalProperties?: Record<string, unknown>;
}

export const depositBalancesSchema: Schema<DepositBalances> = typedExpandoObject(
  {
    accountId: ['accountId', optional(string())],
    accountType: ['accountType', optional(string())],
    accountNumberDisplay: ['accountNumberDisplay', optional(string())],
    currency: ['currency', optional(lazy(() => currencyEntitySchema))],
    description: ['description', optional(string())],
    fiAttributes: [
      'fiAttributes',
      optional(array(lazy(() => fiAttributeEntitySchema))),
    ],
    nickname: ['nickname', optional(string())],
    productName: ['productName', optional(string())],
    status: ['status', optional(accountInfoStatusSchema)],
    lineOfBusiness: ['lineOfBusiness', optional(string())],
    balanceType: ['balanceType', optional(balanceTypeSchema)],
    interestRate: ['interestRate', optional(number())],
    interestRateType: ['interestRateType', optional(interestRateTypeSchema)],
    interestRateAsOf: ['interestRateAsOf', optional(string())],
    lastActivityDate: ['lastActivityDate', optional(string())],
    micrNumber: ['micrNumber', optional(string())],
    parentAccountId: ['parentAccountId', optional(string())],
    priorInterestRate: ['priorInterestRate', optional(number())],
    transferIn: ['transferIn', optional(boolean())],
    transferOut: ['transferOut', optional(boolean())],
    annualPercentageYield: ['annualPercentageYield', optional(number())],
    term: ['term', optional(number())],
    maturityDate: ['maturityDate', optional(string())],
    balanceAsOf: ['balanceAsOf', optional(string())],
    openingDayBalance: ['openingDayBalance', optional(number())],
    availableBalance: ['availableBalance', optional(number())],
    interestYtd: ['interestYtd', optional(number())],
    currentBalance: ['currentBalance', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
