/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { DepositAccount, depositAccountSchema } from './depositAccount';

export interface DepositAccountInfo {
  /** Deposit Account */
  depositAccount?: DepositAccount;
  additionalProperties?: Record<string, unknown>;
}

export const depositAccountInfoSchema: Schema<DepositAccountInfo> = typedExpandoObject(
  {
    depositAccount: [
      'depositAccount',
      optional(lazy(() => depositAccountSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
