/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DepositTransactionType
 */
export enum DepositTransactionType {
  Check = 'CHECK',
  Withdrawal = 'WITHDRAWAL',
  Transfer = 'TRANSFER',
  Posdebit = 'POSDEBIT',
  Atmwithdrawal = 'ATMWITHDRAWAL',
  Billpayment = 'BILLPAYMENT',
  Fee = 'FEE',
  Deposit = 'DEPOSIT',
  Adjustment = 'ADJUSTMENT',
  Interest = 'INTEREST',
  Dividend = 'DIVIDEND',
  Directdeposit = 'DIRECTDEPOSIT',
  Atmdeposit = 'ATMDEPOSIT',
  Poscredit = 'POSCREDIT',
}

/**
 * Schema for DepositTransactionType
 */
export const depositTransactionTypeSchema: Schema<DepositTransactionType> = stringEnum(
  DepositTransactionType,
  true
);
