/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Description and amount pair used on IRS W-2, etc. */
export interface DescriptionAndAmount {
  /** Description */
  description?: string;
  /** Amount */
  amount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const descriptionAndAmountSchema: Schema<DescriptionAndAmount> = typedExpandoObject(
  {
    description: ['description', optional(string())],
    amount: ['amount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
