/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** The country and region of the business customer's location */
export interface Domicile {
  region?: string;
  country?: string;
  additionalProperties?: Record<string, unknown>;
}

export const domicileSchema: Schema<Domicile> = typedExpandoObject(
  {
    region: ['region', optional(string())],
    country: ['country', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
