/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** An error entity which can be used at the API level for error responses or at the account level to indicate a problem specific to a particular account. See the error codes and descriptions defined in the latest FDX API Specification document, section 6.2 Errors */
export interface Error {
  /** Error code defined by FDX API Specification or Data Provider indicating the error situation which has occurred */
  code?: number;
  /** End user displayable information which might help the customer diagnose an error */
  message?: string;
  /** Message used to debug the root cause of the error. Contents should not be used in consumer's business logic. Can change at any time and should only be used for consumer to communicate with the data provider about an issue. Provider can include an error GUID in message for their use. */
  debugMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorSchema: Schema<Error> = typedExpandoObject(
  {
    code: ['code', optional(number())],
    message: ['message', optional(string())],
    debugMessage: ['debugMessage', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
