/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExpiredOptionType
 */
export enum ExpiredOptionType {
  Granted = 'GRANTED',
  Purchased = 'PURCHASED',
}

/**
 * Schema for ExpiredOptionType
 */
export const expiredOptionTypeSchema: Schema<ExpiredOptionType> = stringEnum(
  ExpiredOptionType,
  true
);
