/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { DateAndAmount, dateAndAmountSchema } from './dateAndAmount';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Farm Income Statement for IRS Form 1040 Schedule F */
export interface FarmIncomeStatement {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Box A, Principal crop or activity */
  cropOrActivity?: string;
  /** Box 1a, Sales of livestock and other resale items */
  sales?: number;
  /** Box 1b, Cost or other basis of livestock or other items */
  costOfItemsSold?: number;
  /** Box 2, Sales of livestock, produce, grains, and other products you raised */
  salesOfRaised?: number;
  /** Box 3a, Cooperative distributions */
  coopDistributions?: number;
  /** Box 4a, Agricultural program payments */
  agProgramPayments?: number;
  /** Box 5a, Commodity Credit Corporation (CCC) loans reported under election */
  cccLoans?: number;
  /** Box 6a, Crop insurance proceeds and federal crop disaster payments */
  cropInsuranceProceeds?: number;
  /** Box 7, Custom hire (machine work) income */
  customHireIncome?: number;
  /** Box 8, Other income */
  otherIncome?: DescriptionAndAmount[];
  /** Box 10, Car and truck expenses */
  carAndTruck?: number;
  /** Box 11, Chemicals */
  chemicals?: number;
  /** Box 12, Conservation expenses */
  conservation?: number;
  /** Box 13, Custom hire (machine work) */
  customHireExpenses?: number;
  /** Box 14, Depreciation */
  depreciation?: number;
  /** Box 15, Employee benefit programs */
  employeeBenefitPrograms?: number;
  /** Box 16, Feed */
  feed?: number;
  /** Box 17, Fertilizers and lime */
  fertilizers?: number;
  /** Box 18, Freight and trucking */
  freight?: number;
  /** Box 19, Gasoline, fuel, and oil */
  fuel?: number;
  /** Box 20, Insurance (other than health) */
  insurance?: number;
  /** Box 21a, Mortgage Interest */
  mortgageInterest?: number;
  /** Box 21b, Other interest */
  otherInterest?: number;
  /** Box 22, Labor hired */
  laborHired?: number;
  /** Box 23, Pension and profit-sharing plans */
  pension?: number;
  /** Box 24a, Rent or lease: Vehicles, machinery, equipment */
  equipmentRent?: number;
  /** Box 24b, Rent or lease: Other */
  otherRent?: number;
  /** Box 25, Repairs and maintenance */
  repairs?: number;
  /** Box 26, Seeds and plants */
  seeds?: number;
  /** Box 27, Storage and warehousing */
  storage?: number;
  /** Box 28, Supplies */
  supplies?: number;
  /** Box 29, Taxes */
  taxes?: number;
  /** Box 30, Utilities */
  utilities?: number;
  /** Box 31, Veterinary, breeding, and medicine */
  veterinary?: number;
  /** Box 32, Other expenses */
  otherExpenses?: DescriptionAndAmount[];
  /** Capital expenditures, for use in calculating Depreciation */
  capitalExpenditures?: DateAndAmount[];
  additionalProperties?: Record<string, unknown>;
}

export const farmIncomeStatementSchema: Schema<FarmIncomeStatement> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    cropOrActivity: ['cropOrActivity', optional(string())],
    sales: ['sales', optional(number())],
    costOfItemsSold: ['costOfItemsSold', optional(number())],
    salesOfRaised: ['salesOfRaised', optional(number())],
    coopDistributions: ['coopDistributions', optional(number())],
    agProgramPayments: ['agProgramPayments', optional(number())],
    cccLoans: ['cccLoans', optional(number())],
    cropInsuranceProceeds: ['cropInsuranceProceeds', optional(number())],
    customHireIncome: ['customHireIncome', optional(number())],
    otherIncome: [
      'otherIncome',
      optional(array(lazy(() => descriptionAndAmountSchema))),
    ],
    carAndTruck: ['carAndTruck', optional(number())],
    chemicals: ['chemicals', optional(number())],
    conservation: ['conservation', optional(number())],
    customHireExpenses: ['customHireExpenses', optional(number())],
    depreciation: ['depreciation', optional(number())],
    employeeBenefitPrograms: ['employeeBenefitPrograms', optional(number())],
    feed: ['feed', optional(number())],
    fertilizers: ['fertilizers', optional(number())],
    freight: ['freight', optional(number())],
    fuel: ['fuel', optional(number())],
    insurance: ['insurance', optional(number())],
    mortgageInterest: ['mortgageInterest', optional(number())],
    otherInterest: ['otherInterest', optional(number())],
    laborHired: ['laborHired', optional(number())],
    pension: ['pension', optional(number())],
    equipmentRent: ['equipmentRent', optional(number())],
    otherRent: ['otherRent', optional(number())],
    repairs: ['repairs', optional(number())],
    seeds: ['seeds', optional(number())],
    storage: ['storage', optional(number())],
    supplies: ['supplies', optional(number())],
    taxes: ['taxes', optional(number())],
    utilities: ['utilities', optional(number())],
    veterinary: ['veterinary', optional(number())],
    otherExpenses: [
      'otherExpenses',
      optional(array(lazy(() => descriptionAndAmountSchema))),
    ],
    capitalExpenditures: [
      'capitalExpenditures',
      optional(array(lazy(() => dateAndAmountSchema))),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
