/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface FiAssetClassItem {
  /** FI-specific asset class */
  assetClass?: string;
  /** Percentage of asset class that falls under this asset */
  percent?: number;
  additionalProperties?: Record<string, unknown>;
}

export const fiAssetClassItemSchema: Schema<FiAssetClassItem> = typedExpandoObject(
  {
    assetClass: ['assetClass', optional(string())],
    percent: ['percent', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
