/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Data provider-specific attribute */
export interface FiAttributeEntity {
  /** Name of attribute */
  name?: string;
  /** Value of attribute */
  value?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fiAttributeEntitySchema: Schema<FiAttributeEntity> = typedExpandoObject(
  { name: ['name', optional(string())], value: ['value', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
