/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Address, addressSchema } from './address';
import { BusinessName, businessNameSchema } from './businessName';
import { IndividualName, individualNameSchema } from './individualName';
import { TaxPartyType, taxPartyTypeSchema } from './taxPartyType';
import {
  TelephoneNumberPlusExtension,
  telephoneNumberPlusExtensionSchema,
} from './telephoneNumberPlusExtension';

/** Boxes 13a-j, 13l, Recipient for Form 1042-S */
export interface Form1042SRecipient {
  /** Issuer or recipient Tax Identification Number. Usually EIN for issuer and SSN for recipient */
  tin?: string;
  /** Type of issuer or recipient legal entity, as "BUSINESS" or "INDIVIDUAL". Commonly BUSINESS for issuer and INDIVIDUAL for recipient */
  partyType?: TaxPartyType;
  /** Individual issuer or recipient name */
  individualName?: IndividualName;
  /** Business issuer or recipient name */
  businessName?: BusinessName;
  /** Issuer or recipient address */
  address?: Address;
  /** Issuer or recipient telephone number */
  phone?: TelephoneNumberPlusExtension;
  /** Issuer or recipient email address. (Additional information, not part of IRS forms) */
  email?: string;
  /**
   * Ch. 3 status code,
   *   * Box 12b, Withholding Agent,
   *   * Box 13f, Recipient,
   *   * Box 15b, Intermediary or flow-through entity,
   *   * Box 16d, Payer
   */
  ch3StatusCode?: string;
  /**
   * Ch. 4 status code,
   *   * Box 12c, Withholding Agent,
   *   * Box 13g, Recipient,
   *   * Box 15c, Intermediary or flow-through entity,
   *   * Box 16e, Payer
   */
  ch4StatusCode?: string;
  /**
   * Agent's Global Intermediary Identification Number (GIIN),
   *   * Box 12e, Withholding Agent,
   *   * Box 13h, Recipient,
   *   * Box 15e, Intermediary or flow-through entity,
   *   * Box 16c, Payer
   */
  giin?: string;
  /**
   * Foreign tax identification number, if any,
   *   * Box 12g, Withholding Agent,
   *   * Box 13i, Recipient,
   *   * Box 15g, Intermediary or flow-through entity
   */
  foreignTin?: string;
  /** Box 13j, Recipient's LOB code, if any */
  lobCode?: string;
  /** Box 13l, Recipient's date of birth */
  dateOfBirth?: string;
  additionalProperties?: Record<string, unknown>;
}

export const form1042SRecipientSchema: Schema<Form1042SRecipient> = typedExpandoObject(
  {
    tin: ['tin', optional(string())],
    partyType: ['partyType', optional(taxPartyTypeSchema)],
    individualName: [
      'individualName',
      optional(lazy(() => individualNameSchema)),
    ],
    businessName: ['businessName', optional(lazy(() => businessNameSchema))],
    address: ['address', optional(lazy(() => addressSchema))],
    phone: ['phone', optional(lazy(() => telephoneNumberPlusExtensionSchema))],
    email: ['email', optional(string())],
    ch3StatusCode: ['ch3StatusCode', optional(string())],
    ch4StatusCode: ['ch4StatusCode', optional(string())],
    giin: ['giin', optional(string())],
    foreignTin: ['foreignTin', optional(string())],
    lobCode: ['lobCode', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
