/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Taxable Distributions Received From Cooperatives */
export interface Form1099Patr {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Patronage dividends */
  patronageDividends?: number;
  /** Box 2, Nonpatronage distributions */
  nonpatronageDistributions?: number;
  /** Box 3, Per-unit retain allocations */
  perUnitRetainAllocations?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Redemption of nonqualified notices and retain allocations */
  redemption?: number;
  /** Box 6, Section 199A(g) deduction */
  section199Deduction?: number;
  /** Box 7, Qualified payments */
  qualifiedPayments?: number;
  /** Box 8, Section 199A(a) qualified items */
  section199QualifiedItems?: number;
  /** Box 9, Section 199A(a) SSTB (Specified Service Trade or Business) items */
  section199SstbItems?: number;
  /** Box 10, Investment credit */
  investmentCredit?: number;
  /** Box 11, Work opportunity credit */
  workOpportunityCredit?: number;
  /** Box 12, Other credits and deductions */
  otherCreditsAndDeductions?: number;
  /** Box 13, Specified Cooperative */
  specifiedCoop?: boolean;
  /** State and Local tax withholding, from IRS's IRIS schema */
  stateAndLocal?: StateAndLocalTaxWithholding;
  /** Second TIN Notice */
  secondTinNotice?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const form1099PatrSchema: Schema<Form1099Patr> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    accountNumber: ['accountNumber', optional(string())],
    patronageDividends: ['patronageDividends', optional(number())],
    nonpatronageDistributions: [
      'nonpatronageDistributions',
      optional(number()),
    ],
    perUnitRetainAllocations: ['perUnitRetainAllocations', optional(number())],
    federalTaxWithheld: ['federalTaxWithheld', optional(number())],
    redemption: ['redemption', optional(number())],
    section199Deduction: ['section199Deduction', optional(number())],
    qualifiedPayments: ['qualifiedPayments', optional(number())],
    section199QualifiedItems: ['section199QualifiedItems', optional(number())],
    section199SstbItems: ['section199SstbItems', optional(number())],
    investmentCredit: ['investmentCredit', optional(number())],
    workOpportunityCredit: ['workOpportunityCredit', optional(number())],
    otherCreditsAndDeductions: [
      'otherCreditsAndDeductions',
      optional(number()),
    ],
    specifiedCoop: ['specifiedCoop', optional(boolean())],
    stateAndLocal: [
      'stateAndLocal',
      optional(lazy(() => stateAndLocalTaxWithholdingSchema)),
    ],
    secondTinNotice: ['secondTinNotice', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
