/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Tuition Statement */
export interface Form1098T {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** By checking the box in STUDENT'S TIN, filer is making a true and accurate certification under penalty of perjury that they have complied with standards promulgated by the Secretary for obtaining such individual's TIN */
  studentTinCertification?: boolean;
  /** Account number */
  accountNumber?: string;
  /** Box 8, Check if at least half-time student */
  halfTime?: boolean;
  /** Box 1, Payments received for qualified tuition and related expenses */
  qualifiedTuitionFees?: number;
  /** Box 4, Adjustments made for a prior year */
  adjustmentPriorYear?: number;
  /** Box 5, Scholarships or grants */
  scholarship?: number;
  /** Box 6, Adjustments to scholarships or grants for a prior year */
  adjustScholarship?: number;
  /** Box 7, Check if the amount in box 1 or box 2 includes amounts for an academic period beginning January - March of next year */
  includeJanMar?: boolean;
  /** Box 9, Check if graduate student */
  graduate?: boolean;
  /** Box 10, Insurance contract reimbursement / refund */
  insuranceRefund?: number;
  additionalProperties?: Record<string, unknown>;
}

export const form1098TSchema: Schema<Form1098T> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    studentTinCertification: ['studentTinCertification', optional(boolean())],
    accountNumber: ['accountNumber', optional(string())],
    halfTime: ['halfTime', optional(boolean())],
    qualifiedTuitionFees: ['qualifiedTuitionFees', optional(number())],
    adjustmentPriorYear: ['adjustmentPriorYear', optional(number())],
    scholarship: ['scholarship', optional(number())],
    adjustScholarship: ['adjustScholarship', optional(number())],
    includeJanMar: ['includeJanMar', optional(boolean())],
    graduate: ['graduate', optional(boolean())],
    insuranceRefund: ['insuranceRefund', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
