/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Notice to Shareholder of Undistributed Long-Term Capital Gains */
export interface Form2439 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Fiscal year begin date */
  fiscalYearBegin?: string;
  /** Fiscal year end date */
  fiscalYearEnd?: string;
  /** Box 1a, Total undistributed long-term capital gains */
  undistributedLongTermCapitalGains?: number;
  /** Box 1b, Unrecaptured section 1250 gain */
  unrecaptured1250Gain?: number;
  /** Box 1c, Section 1202 gain */
  section1202Gain?: number;
  /** Box 1d, Collectibles (28%) gain */
  collectiblesGain?: number;
  /** Box 2, Tax paid by the RIC or REIT on the box 1a gains */
  taxPaid?: number;
  additionalProperties?: Record<string, unknown>;
}

export const form2439Schema: Schema<Form2439> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    fiscalYearBegin: ['fiscalYearBegin', optional(string())],
    fiscalYearEnd: ['fiscalYearEnd', optional(string())],
    undistributedLongTermCapitalGains: [
      'undistributedLongTermCapitalGains',
      optional(number()),
    ],
    unrecaptured1250Gain: ['unrecaptured1250Gain', optional(number())],
    section1202Gain: ['section1202Gain', optional(number())],
    collectiblesGain: ['collectiblesGain', optional(number())],
    taxPaid: ['taxPaid', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
