/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Cancellation of Debt */
export interface Form1099C {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Date of identifiable event */
  dateOfEvent?: string;
  /** Box 2, Amount of debt discharged */
  amountDischarged?: number;
  /** Box 3, Interest if included in box 2 */
  interestIncluded?: number;
  /** Box 4, Debt description */
  debtDescription?: string;
  /** Box 5, If checked, the debtor was personally liable for repayment of the debt */
  personallyLiable?: boolean;
  /** Box 6, Identifiable debt code */
  debtCode?: string;
  /** Box 7, Fair market value of property */
  fairMarketValue?: number;
  additionalProperties?: Record<string, unknown>;
}

export const form1099CSchema: Schema<Form1099C> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    accountNumber: ['accountNumber', optional(string())],
    dateOfEvent: ['dateOfEvent', optional(string())],
    amountDischarged: ['amountDischarged', optional(number())],
    interestIncluded: ['interestIncluded', optional(number())],
    debtDescription: ['debtDescription', optional(string())],
    personallyLiable: ['personallyLiable', optional(boolean())],
    debtCode: ['debtCode', optional(string())],
    fairMarketValue: ['fairMarketValue', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
