/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Original Issue Discount */
export interface Form1099Oid {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** FATCA filing requirement */
  foreignAccountTaxCompliance?: boolean;
  /** Account number */
  accountNumber?: string;
  /** Box 1, Original issue discount */
  originalIssueDiscount?: number;
  /** Box 2, Other periodic interest */
  otherPeriodicInterest?: number;
  /** Box 3, Early withdrawal penalty */
  earlyWithdrawalPenalty?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Market discount */
  marketDiscount?: number;
  /** Box 6, Acquisition premium */
  acquisitionPremium?: number;
  /** Box 7, Description */
  oidDescription?: string;
  /** Box 8, Original issue discount on U.S. Treasury obligations */
  discountOnTreasuryObligations?: number;
  /** Box 9, Investment expenses */
  investmentExpenses?: number;
  /** Box 10, Bond premium */
  bondPremium?: number;
  /** Box 11, Tax-exempt OID */
  taxExemptOid?: number;
  /** Boxes 12-14, State and Local tax withheld */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Supplemental: State name and tax-exempt OID by state */
  stateExemptOid?: DescriptionAndAmount[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const form1099OidSchema: Schema<Form1099Oid> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    foreignAccountTaxCompliance: [
      'foreignAccountTaxCompliance',
      optional(boolean()),
    ],
    accountNumber: ['accountNumber', optional(string())],
    originalIssueDiscount: ['originalIssueDiscount', optional(number())],
    otherPeriodicInterest: ['otherPeriodicInterest', optional(number())],
    earlyWithdrawalPenalty: ['earlyWithdrawalPenalty', optional(number())],
    federalTaxWithheld: ['federalTaxWithheld', optional(number())],
    marketDiscount: ['marketDiscount', optional(number())],
    acquisitionPremium: ['acquisitionPremium', optional(number())],
    oidDescription: ['oidDescription', optional(string())],
    discountOnTreasuryObligations: [
      'discountOnTreasuryObligations',
      optional(number()),
    ],
    investmentExpenses: ['investmentExpenses', optional(number())],
    bondPremium: ['bondPremium', optional(number())],
    taxExemptOid: ['taxExemptOid', optional(number())],
    stateAndLocal: [
      'stateAndLocal',
      optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
    ],
    stateExemptOid: [
      'stateExemptOid',
      optional(array(lazy(() => descriptionAndAmountSchema))),
    ],
    secondTinNotice: ['secondTinNotice', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
