/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Miscellaneous Income */
export interface Form1099Misc {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Rents */
  rents?: number;
  /** Box 2, Royalties */
  royalties?: number;
  /** Box 3, Other income */
  otherIncome?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Fishing boat proceeds */
  fishingBoatProceeds?: number;
  /** Box 6, Medical and health care payments */
  medicalHealthPayment?: number;
  /** Box 7, Payer made direct sales of $5,000 or more of consumer products to a buyer (recipient) for resale */
  payerDirectSales?: boolean;
  /** Box 8, Substitute payments in lieu of dividends or interest */
  substitutePayments?: number;
  /** Box 9, Crop insurance proceeds */
  cropInsurance?: number;
  /** Second TIN Notice */
  secondTinNotice?: boolean;
  /** Box 10, Gross proceeds paid to an attorney */
  grossAttorney?: number;
  /** Box 11, Fish purchased for resale */
  fishPurchased?: number;
  /** Box 12, Section 409A deferrals */
  section409ADeferrals?: number;
  /** Box 13, FATCA filing requirement */
  foreignAccountTaxCompliance?: boolean;
  /** Box 14, Excess golden parachute payments */
  excessGolden?: number;
  /** Box 15, Nonqualified Deferred Compensation */
  nonQualifiedDeferredCompensation?: number;
  /** Boxes 16-18, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  additionalProperties?: Record<string, unknown>;
}

export const form1099MiscSchema: Schema<Form1099Misc> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    accountNumber: ['accountNumber', optional(string())],
    rents: ['rents', optional(number())],
    royalties: ['royalties', optional(number())],
    otherIncome: ['otherIncome', optional(number())],
    federalTaxWithheld: ['federalTaxWithheld', optional(number())],
    fishingBoatProceeds: ['fishingBoatProceeds', optional(number())],
    medicalHealthPayment: ['medicalHealthPayment', optional(number())],
    payerDirectSales: ['payerDirectSales', optional(boolean())],
    substitutePayments: ['substitutePayments', optional(number())],
    cropInsurance: ['cropInsurance', optional(number())],
    secondTinNotice: ['secondTinNotice', optional(boolean())],
    grossAttorney: ['grossAttorney', optional(number())],
    fishPurchased: ['fishPurchased', optional(number())],
    section409ADeferrals: ['section409ADeferrals', optional(number())],
    foreignAccountTaxCompliance: [
      'foreignAccountTaxCompliance',
      optional(boolean()),
    ],
    excessGolden: ['excessGolden', optional(number())],
    nonQualifiedDeferredCompensation: [
      'nonQualifiedDeferredCompensation',
      optional(number()),
    ],
    stateAndLocal: [
      'stateAndLocal',
      optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
