/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Error, errorSchema } from './error';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';
import { NameAndAddress, nameAndAddressSchema } from './nameAndAddress';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty, taxPartySchema } from './taxParty';
import { TypeFormType, typeFormTypeSchema } from './typeFormType';

/** Long-Term Care and Accelerated Death Benefits */
export interface Form1099Ltc {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HateoasLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Gross long-term care benefits paid */
  ltcBenefits?: number;
  /** Box 2, Accelerated death benefits paid */
  deathBenefits?: number;
  /** Box 3, Per diem */
  perDiem?: boolean;
  /** Box 3, Reimbursed amount */
  reimbursedAmount?: boolean;
  /** INSURED'S taxpayer identification no. */
  insuredId?: string;
  /** Insured name and address */
  insuredNameAddress?: NameAndAddress;
  /** Box 4, Qualified contract */
  qualifiedContract?: boolean;
  /** Box 5, Chronically ill */
  chronicallyIll?: boolean;
  /** Box 5, Terminally ill */
  terminallyIll?: boolean;
  /** Date certified */
  dateCertified?: string;
  additionalProperties?: Record<string, unknown>;
}

export const form1099LtcSchema: Schema<Form1099Ltc> = typedExpandoObject(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormTypeSchema)],
    issuer: ['issuer', optional(lazy(() => taxPartySchema))],
    recipient: ['recipient', optional(lazy(() => taxPartySchema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => errorSchema))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    accountNumber: ['accountNumber', optional(string())],
    ltcBenefits: ['ltcBenefits', optional(number())],
    deathBenefits: ['deathBenefits', optional(number())],
    perDiem: ['perDiem', optional(boolean())],
    reimbursedAmount: ['reimbursedAmount', optional(boolean())],
    insuredId: ['insuredId', optional(string())],
    insuredNameAddress: [
      'insuredNameAddress',
      optional(lazy(() => nameAndAddressSchema)),
    ],
    qualifiedContract: ['qualifiedContract', optional(boolean())],
    chronicallyIll: ['chronicallyIll', optional(boolean())],
    terminallyIll: ['terminallyIll', optional(boolean())],
    dateCertified: ['dateCertified', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
