/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Frequency
 */
export enum Frequency {
  Annually = 'ANNUALLY',
  Biweekly = 'BIWEEKLY',
  Daily = 'DAILY',
  Monthly = 'MONTHLY',
  Semiannually = 'SEMIANNUALLY',
  Semimonthly = 'SEMIMONTHLY',
  Weekly = 'WEEKLY',
}

/**
 * Schema for Frequency
 */
export const frequencySchema: Schema<Frequency> = stringEnum(Frequency, true);
