/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { IndividualName, individualNameSchema } from './individualName';
import {
  MonthAbbreviation,
  monthAbbreviationSchema,
} from './monthAbbreviation';

/** Used on Form 1095-B Part IV and Form 1095-C Part III */
export interface HealthInsuranceCoveredIndividual {
  /** Name of responsible individual */
  name?: IndividualName;
  /** Social security number or other TIN */
  tin?: string;
  /** Date of birth */
  dateOfBirth?: string;
  /** Covered all 12 months */
  coveredAll12Months?: boolean;
  /** Months covered */
  coveredMonths?: MonthAbbreviation[];
  additionalProperties?: Record<string, unknown>;
}

export const healthInsuranceCoveredIndividualSchema: Schema<HealthInsuranceCoveredIndividual> = typedExpandoObject(
  {
    name: ['name', optional(lazy(() => individualNameSchema))],
    tin: ['tin', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
    coveredAll12Months: ['coveredAll12Months', optional(boolean())],
    coveredMonths: ['coveredMonths', optional(array(monthAbbreviationSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
