/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { CoverageMonth, coverageMonthSchema } from './coverageMonth';

/** Used on Form 1095-A Part III */
export interface HealthInsuranceCoverage {
  /** Monthly enrollment premiums */
  enrollmentPremium?: number;
  /** Monthly second lowest cost silver plan (SLCSP) premium */
  slcspPremium?: number;
  /** Monthly advance payment of premium tax credit */
  advancePremiumTaxCreditPayment?: number;
  /** Month of coverage */
  month?: CoverageMonth;
  additionalProperties?: Record<string, unknown>;
}

export const healthInsuranceCoverageSchema: Schema<HealthInsuranceCoverage> = typedExpandoObject(
  {
    enrollmentPremium: ['enrollmentPremium', optional(number())],
    slcspPremium: ['slcspPremium', optional(number())],
    advancePremiumTaxCreditPayment: [
      'advancePremiumTaxCreditPayment',
      optional(number()),
    ],
    month: ['month', optional(coverageMonthSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
