/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Used on Form 1095-A Part II */
export interface HealthInsuranceMarketplaceCoveredIndividual {
  /** Covered individual name */
  name?: string;
  /** Covered individual SSN */
  tin?: string;
  /** Covered individual date of birth */
  dateOfBirth?: string;
  /** Coverage start date */
  policyStartDate?: string;
  /** Coverage termination date */
  policyTerminationDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const healthInsuranceMarketplaceCoveredIndividualSchema: Schema<HealthInsuranceMarketplaceCoveredIndividual> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    tin: ['tin', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
    policyStartDate: ['policyStartDate', optional(string())],
    policyTerminationDate: ['policyTerminationDate', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
