/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HeldInAccount
 */
export enum HeldInAccount {
  Cash = 'CASH',
  Margin = 'MARGIN',
  Short = 'SHORT',
  Other = 'OTHER',
}

/**
 * Schema for HeldInAccount
 */
export const heldInAccountSchema: Schema<HeldInAccount> = stringEnum(
  HeldInAccount,
  true
);
