/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Items, itemsSchema } from './items';
import { SecurityIdType, securityIdTypeSchema } from './securityIdType';

export interface Holding {
  /** Long term persistent identity of the holding */
  holdingId?: string;
  /** Unique identifier of the security. */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdType;
  /** Breakdown by tax lot. */
  taxLots?: Items[];
  additionalProperties?: Record<string, unknown>;
}

export const holdingSchema: Schema<Holding> = typedExpandoObject(
  {
    holdingId: ['holdingId', optional(string())],
    securityId: ['securityId', optional(string())],
    securityIdType: ['securityIdType', optional(securityIdTypeSchema)],
    taxLots: ['taxLots', optional(array(lazy(() => itemsSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
