/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HoldingType
 */
export enum HoldingType {
  Stock = 'STOCK',
  Bond = 'BOND',
  Mutualfund = 'MUTUALFUND',
  Cd = 'CD',
  Annuity = 'ANNUITY',
  Option = 'OPTION',
  Other = 'OTHER',
}

/**
 * Schema for HoldingType
 */
export const holdingTypeSchema: Schema<HoldingType> = stringEnum(
  HoldingType,
  true
);
