/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HoldingSubType
 */
export enum HoldingSubType {
  Moneymarket = 'MONEYMARKET',
  Cash = 'CASH',
}

/**
 * Schema for HoldingSubType
 */
export const holdingSubTypeSchema: Schema<HoldingSubType> = stringEnum(
  HoldingSubType,
  true
);
