/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface HrefLink {
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const hrefLinkSchema: Schema<HrefLink> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
