/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncomeType
 */
export enum IncomeType {
  Cglong = 'CGLONG',
  Cgshort = 'CGSHORT',
  Misc = 'MISC',
}

/**
 * Schema for IncomeType
 */
export const incomeTypeSchema: Schema<IncomeType> = stringEnum(
  IncomeType,
  true
);
