/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Name of responsible individual */
export interface IndividualName {
  /** First name */
  first?: string;
  /** Middle initial */
  middle?: string;
  /** Last name */
  last?: string;
  /** Generational or academic suffix */
  suffix?: string;
  additionalProperties?: Record<string, unknown>;
}

export const individualNameSchema: Schema<IndividualName> = typedExpandoObject(
  {
    first: ['first', optional(string())],
    middle: ['middle', optional(string())],
    last: ['last', optional(string())],
    suffix: ['suffix', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
