/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Industry code and type */
export interface IndustryCode {
  type?: string;
  code?: string;
  additionalProperties?: Record<string, unknown>;
}

export const industryCodeSchema: Schema<IndustryCode> = typedExpandoObject(
  { type: ['type', optional(string())], code: ['code', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
