/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InsuranceTransactionType
 */
export enum InsuranceTransactionType {
  Payment = 'PAYMENT',
  Fee = 'FEE',
  Adjustment = 'ADJUSTMENT',
  Interest = 'INTEREST',
}

/**
 * Schema for InsuranceTransactionType
 */
export const insuranceTransactionTypeSchema: Schema<InsuranceTransactionType> = stringEnum(
  InsuranceTransactionType,
  true
);
