/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  InsuranceTransaction,
  insuranceTransactionSchema,
} from './insuranceTransaction';

export interface InsuranceTransactionInfo {
  /** Insurance transactions */
  insuranceTransaction?: InsuranceTransaction;
  additionalProperties?: Record<string, unknown>;
}

export const insuranceTransactionInfoSchema: Schema<InsuranceTransactionInfo> = typedExpandoObject(
  {
    insuranceTransaction: [
      'insuranceTransaction',
      optional(lazy(() => insuranceTransactionSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
