/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InterestRateType
 */
export enum InterestRateType {
  Fixed = 'FIXED',
  Variable = 'VARIABLE',
}

/**
 * Schema for InterestRateType
 */
export const interestRateTypeSchema: Schema<InterestRateType> = stringEnum(
  InterestRateType,
  true
);
