/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InteractionType
 */
export enum InteractionType {
  User = 'user',
  Batch = 'batch',
}

/**
 * Schema for InteractionType
 */
export const interactionTypeSchema: Schema<InteractionType> = stringEnum(
  InteractionType,
  true
);
