/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Inv401KSurce
 */
export enum Inv401KSurce {
  Pretax = 'PRETAX',
  Aftertax = 'AFTERTAX',
  Match = 'MATCH',
  Profitsharing = 'PROFITSHARING',
  Rollover = 'ROLLOVER',
  Othervest = 'OTHERVEST',
  Othernonvest = 'OTHERNONVEST',
}

/**
 * Schema for Inv401KSurce
 */
export const inv401KSurceSchema: Schema<Inv401KSurce> = stringEnum(
  Inv401KSurce,
  true
);
