/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Inv401KSource
 */
export enum Inv401KSource {
  Aftertax = 'AFTERTAX',
  Match = 'MATCH',
  Othernonvest = 'OTHERNONVEST',
  Othervest = 'OTHERVEST',
  Pretax = 'PRETAX',
  Profitsharing = 'PROFITSHARING',
  Rollover = 'ROLLOVER',
}

/**
 * Schema for Inv401KSource
 */
export const inv401KSourceSchema: Schema<Inv401KSource> = stringEnum(
  Inv401KSource,
  true
);
