/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvestmentTransactionType
 */
export enum InvestmentTransactionType {
  Purchased = 'PURCHASED',
  Sold = 'SOLD',
  Purchasedtocover = 'PURCHASEDTOCOVER',
  Adjustment = 'ADJUSTMENT',
  Purchasetoopen = 'PURCHASETOOPEN',
  Purchasetoclose = 'PURCHASETOCLOSE',
  Soldtoopen = 'SOLDTOOPEN',
  Soldtoclose = 'SOLDTOCLOSE',
  Interest = 'INTEREST',
  Margininterest = 'MARGININTEREST',
  Reinvestofincome = 'REINVESTOFINCOME',
  Returnofcapital = 'RETURNOFCAPITAL',
  Transfer = 'TRANSFER',
  Contribution = 'CONTRIBUTION',
  Fee = 'FEE',
  Optionexercise = 'OPTIONEXERCISE',
  Optionexpiration = 'OPTIONEXPIRATION',
  Dividend = 'DIVIDEND',
  Dividendreinvest = 'DIVIDENDREINVEST',
  Split = 'SPLIT',
  Closure = 'CLOSURE',
  Income = 'INCOME',
  Expense = 'EXPENSE',
  Closureopt = 'CLOSUREOPT',
  Invexpense = 'INVEXPENSE',
  Jrnlsec = 'JRNLSEC',
  Jrnlfund = 'JRNLFUND',
  Other = 'OTHER',
  Div = 'DIV',
  Srvchg = 'SRVCHG',
  Dep = 'DEP',
  Deposit = 'DEPOSIT',
  Atm = 'ATM',
  Pos = 'POS',
  Xfer = 'XFER',
  Check = 'CHECK',
  Payment = 'PAYMENT',
  Cash = 'CASH',
  Directdep = 'DIRECTDEP',
  Directdebit = 'DIRECTDEBIT',
  Repeatpmt = 'REPEATPMT',
}

/**
 * Schema for InvestmentTransactionType
 */
export const investmentTransactionTypeSchema: Schema<InvestmentTransactionType> = stringEnum(
  InvestmentTransactionType,
  true
);
