/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvestmentBalanceType
 */
export enum InvestmentBalanceType {
  Amount = 'AMOUNT',
  Percentage = 'PERCENTAGE',
}

/**
 * Schema for InvestmentBalanceType
 */
export const investmentBalanceTypeSchema: Schema<InvestmentBalanceType> = stringEnum(
  InvestmentBalanceType,
  true
);
