/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { CurrencyEntity, currencyEntitySchema } from './currencyEntity';
import {
  InvestmentBalanceType,
  investmentBalanceTypeSchema,
} from './investmentBalanceType';

export interface InvestmentBalanceList {
  /** Name of the balance. */
  balanceName?: string;
  /** Description of balance. */
  balanceDescription?: string;
  /** The type of an investment balance. AMOUNT or PERCENTAGE. */
  balanceType?: InvestmentBalanceType;
  /** Value of balance name. */
  balanceValue?: number;
  /** Date as of this balance. */
  balanceDate?: string;
  /** Indicates the currency code used by the account. May also include currency rate. */
  currency?: CurrencyEntity;
  additionalProperties?: Record<string, unknown>;
}

export const investmentBalanceListSchema: Schema<InvestmentBalanceList> = typedExpandoObject(
  {
    balanceName: ['balanceName', optional(string())],
    balanceDescription: ['balanceDescription', optional(string())],
    balanceType: ['balanceType', optional(investmentBalanceTypeSchema)],
    balanceValue: ['balanceValue', optional(number())],
    balanceDate: ['balanceDate', optional(string())],
    currency: ['currency', optional(lazy(() => currencyEntitySchema))],
  },
  'additionalProperties',
  optional(unknown())
);
