/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvestmentSaleType
 */
export enum InvestmentSaleType {
  Cryptocurrency = 'CRYPTOCURRENCY',
  EmployeeStockPurchasePlan = 'EMPLOYEE_STOCK_PURCHASE_PLAN',
  IncentiveStockOption = 'INCENTIVE_STOCK_OPTION',
  NonqualifiedStockOptions = 'NONQUALIFIED_STOCK_OPTIONS',
  Other = 'OTHER',
  RestrictedStock = 'RESTRICTED_STOCK',
  RestrictedStockUnits = 'RESTRICTED_STOCK_UNITS',
}

/**
 * Schema for InvestmentSaleType
 */
export const investmentSaleTypeSchema: Schema<InvestmentSaleType> = stringEnum(
  InvestmentSaleType,
  true
);
