/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvestmentTransactionSecurityIdType
 */
export enum InvestmentTransactionSecurityIdType {
  Busip = 'BUSIP',
  Isin = 'ISIN',
  Sedol = 'SEDOL',
  Sicc = 'SICC',
  Valor = 'VALOR',
  Wkn = 'WKN',
}

/**
 * Schema for InvestmentTransactionSecurityIdType
 */
export const investmentTransactionSecurityIdTypeSchema: Schema<InvestmentTransactionSecurityIdType> = stringEnum(
  InvestmentTransactionSecurityIdType,
  true
);
