/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  InvestmentsDetailsAccounts,
  investmentsDetailsAccountsSchema,
} from './containers/investmentsDetailsAccounts';

export interface InvestmentsDetails {
  /** An array of accounts with entity types dependent on the account type (deposit, investment, loan, line of credit, annuity or insurance) */
  accounts?: InvestmentsDetailsAccounts[];
  additionalProperties?: Record<string, unknown>;
}

export const investmentsDetailsSchema: Schema<InvestmentsDetails> = typedExpandoObject(
  { accounts: ['accounts', optional(array(investmentsDetailsAccountsSchema))] },
  'additionalProperties',
  optional(unknown())
);
