/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  InvestmentTransaction,
  investmentTransactionSchema,
} from './investmentTransaction';

export interface InvestmentTransactionInfo {
  /** Investment Transactions */
  investmentTransaction?: InvestmentTransaction;
  additionalProperties?: Record<string, unknown>;
}

export const investmentTransactionInfoSchema: Schema<InvestmentTransactionInfo> = typedExpandoObject(
  {
    investmentTransaction: [
      'investmentTransaction',
      optional(lazy(() => investmentTransactionSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
