/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { PositionType, positionTypeSchema } from './positionType';

export interface Items {
  /** Total amount of money spent acquiring this lot including any fees or commission expenses incurred. */
  costBasis?: number;
  /** Lot market value */
  currentValue?: number;
  /** Lot acquired date. */
  originalPurchaseDate?: string;
  /** LONG, SHORT. */
  positionType?: PositionType;
  /** Original purchase price. */
  purchasedPrice?: number;
  /** Lot quantity. */
  quantity?: number;
  additionalProperties?: Record<string, unknown>;
}

export const itemsSchema: Schema<Items> = typedExpandoObject(
  {
    costBasis: ['costBasis', optional(number())],
    currentValue: ['currentValue', optional(number())],
    originalPurchaseDate: ['originalPurchaseDate', optional(string())],
    positionType: ['positionType', optional(positionTypeSchema)],
    purchasedPrice: ['purchasedPrice', optional(number())],
    quantity: ['quantity', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
