/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { HateoasLink, hateoasLinkSchema } from './hateoasLink';

export interface LineItem {
  /** The amount of money attributable to this line item */
  amount?: number;
  /** Check number */
  checkNumber?: number;
  /** The description of the line item */
  description?: string;
  /** Array of image identifiers (unique to transaction) used to retrieve images of check or transaction receipt. */
  imageIds?: string[];
  /** Links (unique to this Transaction) used to retrieve images of checks or transaction receipts, or invoke other APIs */
  links?: HateoasLink[];
  /** Secondary item description */
  memo?: string;
  /** A reference number */
  reference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const lineItemSchema: Schema<LineItem> = typedExpandoObject(
  {
    amount: ['amount', optional(number())],
    checkNumber: ['checkNumber', optional(number())],
    description: ['description', optional(string())],
    imageIds: ['imageIds', optional(array(string()))],
    links: ['links', optional(array(lazy(() => hateoasLinkSchema)))],
    memo: ['memo', optional(string())],
    reference: ['reference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
