/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { HrefLink, hrefLinkSchema } from './hrefLink';

export interface Links {
  next?: HrefLink;
  prev?: HrefLink;
  additionalProperties?: Record<string, unknown>;
}

export const linksSchema: Schema<Links> = typedExpandoObject(
  {
    next: ['next', optional(lazy(() => hrefLinkSchema))],
    prev: ['prev', optional(lazy(() => hrefLinkSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
