/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { LoanBalances, loanBalancesSchema } from './loanBalances';

export interface LoanBalanceInfo {
  /** Data elements included with balances specific to loan accounts */
  loanAccount?: LoanBalances;
  additionalProperties?: Record<string, unknown>;
}

export const loanBalanceInfoSchema: Schema<LoanBalanceInfo> = typedExpandoObject(
  { loanAccount: ['loanAccount', optional(lazy(() => loanBalancesSchema))] },
  'additionalProperties',
  optional(unknown())
);
