/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { LoanTransaction, loanTransactionSchema } from './loanTransaction';

export interface LoanTransactionInfo {
  /** Loan Transaction */
  loanTransaction?: LoanTransaction;
  additionalProperties?: Record<string, unknown>;
}

export const loanTransactionInfoSchema: Schema<LoanTransactionInfo> = typedExpandoObject(
  {
    loanTransaction: [
      'loanTransaction',
      optional(lazy(() => loanTransactionSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
