/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LoanPaymentFrequency
 */
export enum LoanPaymentFrequency {
  Weekly = 'WEEKLY',
  Biweekly = 'BIWEEKLY',
  Twicemonthly = 'TWICEMONTHLY',
  Monthly = 'MONTHLY',
  Fourweeks = 'FOURWEEKS',
  Bimonthly = 'BIMONTHLY',
  Quarterly = 'QUARTERLY',
  Semiannually = 'SEMIANNUALLY',
  Annually = 'ANNUALLY',
  Other = 'OTHER',
}

/**
 * Schema for LoanPaymentFrequency
 */
export const loanPaymentFrequencySchema: Schema<LoanPaymentFrequency> = stringEnum(
  LoanPaymentFrequency,
  true
);
