/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { LoanAccount, loanAccountSchema } from './loanAccount';

export interface LoanAccountInfo {
  /** Loan Account */
  loanAccount?: LoanAccount;
  additionalProperties?: Record<string, unknown>;
}

export const loanAccountInfoSchema: Schema<LoanAccountInfo> = typedExpandoObject(
  { loanAccount: ['loanAccount', optional(lazy(() => loanAccountSchema))] },
  'additionalProperties',
  optional(unknown())
);
