/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LoanAccountPaymentFrequency
 */
export enum LoanAccountPaymentFrequency {
  Daily = 'DAILY',
  Weekly = 'WEEKLY',
  Biweekly = 'BIWEEKLY',
  Semimonthly = 'SEMIMONTHLY',
  Monthly = 'MONTHLY',
  Semiannually = 'SEMIANNUALLY',
  Annually = 'ANNUALLY',
}

/**
 * Schema for LoanAccountPaymentFrequency
 */
export const loanAccountPaymentFrequencySchema: Schema<LoanAccountPaymentFrequency> = stringEnum(
  LoanAccountPaymentFrequency,
  true
);
