/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LoanTransactionType
 */
export enum LoanTransactionType {
  Adjustment = 'ADJUSTMENT',
  Fee = 'FEE',
  Interest = 'INTEREST',
  Payment = 'PAYMENT',
}

/**
 * Schema for LoanTransactionType
 */
export const loanTransactionTypeSchema: Schema<LoanTransactionType> = stringEnum(
  LoanTransactionType,
  true
);
