/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  AccountInformation,
  accountInformationSchema,
} from './accountInformation';

export interface LocAccountInfo {
  /** Line of Credit Account */
  locAccount?: AccountInformation;
  additionalProperties?: Record<string, unknown>;
}

export const locAccountInfoSchema: Schema<LocAccountInfo> = typedExpandoObject(
  {
    locAccount: ['locAccount', optional(lazy(() => accountInformationSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
