/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Amount of local income tax withheld, if any */
export interface LocalTaxWithholding {
  /** Amount of local income tax withheld */
  taxWithheld?: number;
  /** Locality name */
  localityName?: string;
  /** Income amount for local tax purposes */
  income?: number;
  additionalProperties?: Record<string, unknown>;
}

export const localTaxWithholdingSchema: Schema<LocalTaxWithholding> = typedExpandoObject(
  {
    taxWithheld: ['taxWithheld', optional(number())],
    localityName: ['localityName', optional(string())],
    income: ['income', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
