/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  LineOfCreditBalances,
  lineOfCreditBalancesSchema,
} from './lineOfCreditBalances';

export interface LocBalanceInfo {
  /** Data elements included with balances specific to line of credit accounts */
  locAccount?: LineOfCreditBalances;
  additionalProperties?: Record<string, unknown>;
}

export const locBalanceInfoSchema: Schema<LocBalanceInfo> = typedExpandoObject(
  {
    locAccount: [
      'locAccount',
      optional(lazy(() => lineOfCreditBalancesSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
