/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { LocTransaction, locTransactionSchema } from './locTransaction';

export interface LocTransactionInfo {
  /** A line of credit transaction of type */
  locTransaction?: LocTransaction;
  additionalProperties?: Record<string, unknown>;
}

export const locTransactionInfoSchema: Schema<LocTransactionInfo> = typedExpandoObject(
  {
    locTransaction: [
      'locTransaction',
      optional(lazy(() => locTransactionSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
