/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MediaType
 */
export enum MediaType {
  EnumApplicationjson = 'application/json',
  EnumApplicationpdf = 'application/pdf',
}

/**
 * Schema for MediaType
 */
export const mediaTypeSchema: Schema<MediaType> = stringEnum(MediaType, true);
