/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Mode
 */
export enum Mode {
  Raw = 'raw',
  Standard = 'standard',
}

/**
 * Schema for Mode
 */
export const modeSchema: Schema<Mode> = stringEnum(Mode, true);
