/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MonthAbbreviation
 */
export enum MonthAbbreviation {
  Jan = 'JAN',
  Feb = 'FEB',
  Mar = 'MAR',
  Apr = 'APR',
  May = 'MAY',
  Jun = 'JUN',
  Jul = 'JUL',
  Aug = 'AUG',
  Sep = 'SEP',
  Oct = 'OCT',
  Nov = 'NOV',
  Dec = 'DEC',
}

/**
 * Schema for MonthAbbreviation
 */
export const monthAbbreviationSchema: Schema<MonthAbbreviation> = stringEnum(
  MonthAbbreviation,
  true
);
