/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { MutualFundType, mutualFundTypeSchema } from './mutualFundType';

/** Information about the mutual fund security specific to the type of security */
export interface MutualFundSecurityEntity {
  /** Mutual fund type */
  mutualFundType?: MutualFundType;
  /** Units in the FI's street name, positive quantity */
  unitsStreet?: number;
  /** Units in user's name directly, positive  quantity */
  unitsUser?: number;
  /** Reinvest dividends */
  reinvestDividends?: boolean;
  /** Reinvest capital gains */
  reinvestCapitalGains?: boolean;
  /** Current yield reported as portion of the fund's assets */
  yield?: number;
  /** As-of date for yield value */
  yieldAsOfDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundSecurityEntitySchema: Schema<MutualFundSecurityEntity> = typedExpandoObject(
  {
    mutualFundType: ['mutualFundType', optional(mutualFundTypeSchema)],
    unitsStreet: ['unitsStreet', optional(number())],
    unitsUser: ['unitsUser', optional(number())],
    reinvestDividends: ['reinvestDividends', optional(boolean())],
    reinvestCapitalGains: ['reinvestCapitalGains', optional(boolean())],
    yield: ['yield', optional(number())],
    yieldAsOfDate: ['yieldAsOfDate', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
