/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MutualFundType
 */
export enum MutualFundType {
  Openend = 'OPENEND',
  Closeend = 'CLOSEEND',
  Other = 'OTHER',
}

/**
 * Schema for MutualFundType
 */
export const mutualFundTypeSchema: Schema<MutualFundType> = stringEnum(
  MutualFundType,
  true
);
