/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  Iso3166CountryCode,
  iso3166CountryCodeSchema,
} from './iso3166CountryCode';

/** Individual or business name with address */
export interface NameAndAddress {
  /** Address line 1 */
  line1?: string;
  /** Address line 2 */
  line2?: string;
  /** Address line 3 */
  line3?: string;
  /** City */
  city?: string;
  /** State, Province, Territory, Canton or Prefecture. From [Universal Postal Union](https://www.upu.int/en/Postal-Solutions/Programmes-Services/Addressing-Solutions#addressing-s42-standard) as of 2-26-2020, [S42 International Address Standards](https://www.upu.int/UPU/media/upu/documents/PostCode/S42_International-Addressing-Standards.pdf). For U.S. addresses can be 2-character code from '#/components/schemas/StateCode' */
  region?: string;
  /** Postal code */
  postalCode?: string;
  /** Country code */
  country?: Iso3166CountryCode;
  /** Name line 1 */
  name1?: string;
  /** Name line 2 */
  name2?: string;
  additionalProperties?: Record<string, unknown>;
}

export const nameAndAddressSchema: Schema<NameAndAddress> = typedExpandoObject(
  {
    line1: ['line1', optional(string())],
    line2: ['line2', optional(string())],
    line3: ['line3', optional(string())],
    city: ['city', optional(string())],
    region: ['region', optional(string())],
    postalCode: ['postalCode', optional(string())],
    country: ['country', optional(iso3166CountryCodeSchema)],
    name1: ['name1', optional(string())],
    name2: ['name2', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
