/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  Iso3166CountryCode,
  iso3166CountryCodeSchema,
} from './iso3166CountryCode';
import {
  TelephoneNumberPlusExtension,
  telephoneNumberPlusExtensionSchema,
} from './telephoneNumberPlusExtension';

/** Contact phone number with name and address */
export interface NameAddressAndPhone {
  /** Address line 1 */
  line1?: string;
  /** Address line 2 */
  line2?: string;
  /** Address line 3 */
  line3?: string;
  /** City */
  city?: string;
  /** State, Province, Territory, Canton or Prefecture. From [Universal Postal Union](https://www.upu.int/en/Postal-Solutions/Programmes-Services/Addressing-Solutions#addressing-s42-standard) as of 2-26-2020, [S42 International Address Standards](https://www.upu.int/UPU/media/upu/documents/PostCode/S42_International-Addressing-Standards.pdf). For U.S. addresses can be 2-character code from '#/components/schemas/StateCode' */
  region?: string;
  /** Postal code */
  postalCode?: string;
  /** Country code */
  country?: Iso3166CountryCode;
  /** Name line 1 */
  name1?: string;
  /** Name line 2 */
  name2?: string;
  /** A telephone number that can contain optional text for an arbitrary length telephone extension number */
  phone?: TelephoneNumberPlusExtension;
  additionalProperties?: Record<string, unknown>;
}

export const nameAddressAndPhoneSchema: Schema<NameAddressAndPhone> = typedExpandoObject(
  {
    line1: ['line1', optional(string())],
    line2: ['line2', optional(string())],
    line3: ['line3', optional(string())],
    city: ['city', optional(string())],
    region: ['region', optional(string())],
    postalCode: ['postalCode', optional(string())],
    country: ['country', optional(iso3166CountryCodeSchema)],
    name1: ['name1', optional(string())],
    name2: ['name2', optional(string())],
    phone: ['phone', optional(lazy(() => telephoneNumberPlusExtensionSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
