/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** The end-user's name */
export interface Name {
  /** First or given name. This data element may contain first & last name if not separated. */
  first?: string;
  middle?: string;
  last?: string;
  additionalProperties?: Record<string, unknown>;
}

export const nameSchema: Schema<Name> = typedExpandoObject(
  {
    first: ['first', optional(string())],
    middle: ['middle', optional(string())],
    last: ['last', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
