/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OauthScope
 */
export enum OauthScope {
  Openid = 'openid',
  Profile = 'profile',
  OfflineAccess = 'offline_access',
}

/**
 * Schema for OauthScope
 */
export const oauthScopeSchema: Schema<OauthScope> = stringEnum(OauthScope);
