/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** OAuth 2 Authorization endpoint response */
export interface OauthToken {
  /** ID Token */
  idToken: string;
  /** Type of access token */
  tokenType: string;
  /** Time in seconds before the access token expires */
  expiresIn?: bigint;
  /**
   * List of scopes granted
   * This is a space-delimited list of strings.
   */
  scope?: string;
  /** Time of token expiry as unix timestamp (UTC) */
  expiry?: bigint;
  /**
   * Refresh token
   * Used to get a new access token when it expires.
   */
  refreshToken?: string;
  additionalProperties?: Record<string, unknown>;
}

export const oauthTokenSchema: Schema<OauthToken> = typedExpandoObject(
  {
    idToken: ['id_token', string()],
    tokenType: ['token_type', string()],
    expiresIn: ['expires_in', optional(bigint())],
    scope: ['scope', optional(string())],
    expiry: ['expiry', optional(bigint())],
    refreshToken: ['refresh_token', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
