/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { CoverageMonth, coverageMonthSchema } from './coverageMonth';

/** Health insurance coverage offer for part II of IRS Form 1095-C */
export interface OfferOfHealthInsuranceCoverage {
  /** Offer of Coverage (enter required code) */
  coverageCode?: string;
  /** Employee required contribution */
  requiredContribution?: number;
  /** Section 4980H Safe Harbor and Other Relief (enter code) */
  section4980HCode?: string;
  /** Box 17, ZIP Code */
  postalCode?: string;
  /** Month */
  month?: CoverageMonth;
  additionalProperties?: Record<string, unknown>;
}

export const offerOfHealthInsuranceCoverageSchema: Schema<OfferOfHealthInsuranceCoverage> = typedExpandoObject(
  {
    coverageCode: ['coverageCode', optional(string())],
    requiredContribution: ['requiredContribution', optional(number())],
    section4980HCode: ['section4980HCode', optional(string())],
    postalCode: ['postalCode', optional(string())],
    month: ['month', optional(coverageMonthSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
