/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Inv401KSource, inv401KSourceSchema } from './inv401KSource';
import { OrderDuration, orderDurationSchema } from './orderDuration';
import { OrderType, orderTypeSchema } from './orderType';
import { SecurityIdType, securityIdTypeSchema } from './securityIdType';
import { SubAccount, subAccountSchema } from './subAccount';
import { UnitType, unitTypeSchema } from './unitType';

/** Information on an open order. */
export interface OpenOrderEntity {
  /** Long term persistent identity of the order. Id for this order transaction. */
  orderId?: string;
  /** Unique identifier of the security. */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdType;
  /** Market symbol */
  symbol?: string;
  /** Description of order */
  description?: string;
  /** Number of units (shares, bonds, etc.) */
  units?: number;
  /** Type of order. */
  orderType?: OrderType;
  /** Order date */
  orderDate?: string;
  /** Unit price */
  unitPrice?: number;
  /** Type of unit. */
  unitType?: UnitType;
  /** This order is good for DAY, GOODTILLCANCEL, IMMEDIATE */
  orderDuration?: OrderDuration;
  subAccount?: SubAccount;
  /** Limit Price */
  limitPrice?: number;
  /** Stop price */
  stopPrice?: number;
  /** For 401(k) accounts, source of money for this order. Default if not present is OTHERNONVEST. */
  inv401KSource?: Inv401KSource;
  additionalProperties?: Record<string, unknown>;
}

export const openOrderEntitySchema: Schema<OpenOrderEntity> = typedExpandoObject(
  {
    orderId: ['orderId', optional(string())],
    securityId: ['securityId', optional(string())],
    securityIdType: ['securityIdType', optional(securityIdTypeSchema)],
    symbol: ['symbol', optional(string())],
    description: ['description', optional(string())],
    units: ['units', optional(number())],
    orderType: ['orderType', optional(orderTypeSchema)],
    orderDate: ['orderDate', optional(string())],
    unitPrice: ['unitPrice', optional(number())],
    unitType: ['unitType', optional(unitTypeSchema)],
    orderDuration: ['orderDuration', optional(orderDurationSchema)],
    subAccount: ['subAccount', optional(subAccountSchema)],
    limitPrice: ['limitPrice', optional(number())],
    stopPrice: ['stopPrice', optional(number())],
    inv401KSource: ['inv401kSource', optional(inv401KSourceSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
