/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { OptionType, optionTypeSchema } from './optionType';
import { Secured, securedSchema } from './secured';

/** Information about the option security specific to the type of security */
export interface OptionSecurityEntity {
  /** How the option is secured */
  secured?: Secured;
  optionType?: OptionType;
  /** Strike price / Unit price */
  strikePrice?: number;
  /** Expiration date of option */
  expireDate?: string;
  /** Shares per contract */
  sharesPerContract?: number;
  additionalProperties?: Record<string, unknown>;
}

export const optionSecurityEntitySchema: Schema<OptionSecurityEntity> = typedExpandoObject(
  {
    secured: ['secured', optional(securedSchema)],
    optionType: ['optionType', optional(optionTypeSchema)],
    strikePrice: ['strikePrice', optional(number())],
    expireDate: ['expireDate', optional(string())],
    sharesPerContract: ['sharesPerContract', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
