/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OptionType
 */
export enum OptionType {
  Call = 'CALL',
  Put = 'PUT',
}

/**
 * Schema for OptionType
 */
export const optionTypeSchema: Schema<OptionType> = stringEnum(
  OptionType,
  true
);
