/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDuration
 */
export enum OrderDuration {
  Day = 'DAY',
  Goodtillcancel = 'GOODTILLCANCEL',
  Immediate = 'IMMEDIATE',
}

/**
 * Schema for OrderDuration
 */
export const orderDurationSchema: Schema<OrderDuration> = stringEnum(
  OrderDuration,
  true
);
