/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderType
 */
export enum OrderType {
  Buy = 'BUY',
  Sell = 'SELL',
  Buytocover = 'BUYTOCOVER',
  Buytoopen = 'BUYTOOPEN',
  Selltocover = 'SELLTOCOVER',
  Selltoopen = 'SELLTOOPEN',
  Sellshort = 'SELLSHORT',
  Sellclose = 'SELLCLOSE',
}

/**
 * Schema for OrderType
 */
export const orderTypeSchema: Schema<OrderType> = stringEnum(OrderType, true);
