/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Information about the security specific to the type of security */
export interface OtherSecurityEntity {
  /** Description of Other Security */
  typeDescription?: string;
  additionalProperties?: Record<string, unknown>;
}

export const otherSecurityEntitySchema: Schema<OtherSecurityEntity> = typedExpandoObject(
  { typeDescription: ['typeDescription', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
