/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** This provides details required to execute a transaction against the account within the payment network */
export interface PaymentNetworkSupportedByAccount {
  /** Bank identifier used by the payment network ie. Routing Number */
  bankId?: string;
  /** The number used to identify the account within the payment network. If identifierType is ACCOUNT_NUMBER, this is the account number. */
  identifier?: string;
  /** Type of identifier */
  identifierType?: string;
  /** Type of payment network */
  type?: string;
  /** Can transfer funds to the account using this information */
  transferIn?: boolean;
  /** Can transfer funds from the account using this information */
  transferOut?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const paymentNetworkSupportedByAccountSchema: Schema<PaymentNetworkSupportedByAccount> = typedExpandoObject(
  {
    bankId: ['bankId', optional(string())],
    identifier: ['identifier', optional(string())],
    identifierType: ['identifierType', optional(string())],
    type: ['type', optional(string())],
    transferIn: ['transferIn', optional(boolean())],
    transferOut: ['transferOut', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
