/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Frequency, frequencySchema } from './frequency';

/** Information about a pension source. */
export interface PensionSourceEntity {
  /** Name of the Source */
  displayName?: string;
  /** Benefit Amount */
  amount?: number;
  /** Form of payment */
  paymentOption?: string;
  /** Date benefit was calculated */
  asOfDate?: string;
  frequency?: Frequency;
  /** Assumed retirement date ‐ As of date amount is payable */
  startDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const pensionSourceEntitySchema: Schema<PensionSourceEntity> = typedExpandoObject(
  {
    displayName: ['displayName', optional(string())],
    amount: ['amount', optional(number())],
    paymentOption: ['paymentOption', optional(string())],
    asOfDate: ['asOfDate', optional(string())],
    frequency: ['frequency', optional(frequencySchema)],
    startDate: ['startDate', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
