/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PeriodCertainGuarantee
 */
export enum PeriodCertainGuarantee {
  EnumNoPeriodCertain = 'NO PERIOD CERTAIN',
  Enum5Year = '5-YEAR',
  Enum10Year = '10-YEAR',
  Enum20Year = '20-YEAR',
  Enum30Year = '30-YEAR',
}

/**
 * Schema for PeriodCertainGuarantee
 */
export const periodCertainGuaranteeSchema: Schema<PeriodCertainGuarantee> = stringEnum(
  PeriodCertainGuarantee,
  true
);
