/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PolicyPremiumTerm
 */
export enum PolicyPremiumTerm {
  Monthly = 'MONTHLY',
  Annual = 'ANNUAL',
}

/**
 * Schema for PolicyPremiumTerm
 */
export const policyPremiumTermSchema: Schema<PolicyPremiumTerm> = stringEnum(
  PolicyPremiumTerm,
  true
);
