/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PositionType
 */
export enum PositionType {
  Long = 'LONG',
  Short = 'SHORT',
}

/**
 * Schema for PositionType
 */
export const positionTypeSchema: Schema<PositionType> = stringEnum(
  PositionType,
  true
);
