/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResultType
 */
export enum ResultType {
  Details = 'details',
  Lightweight = 'lightweight',
}

/**
 * Schema for ResultType
 */
export const resultTypeSchema: Schema<ResultType> = stringEnum(
  ResultType,
  true
);
