/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleProceedsType
 */
export enum SaleProceedsType {
  Gross = 'GROSS',
  Net = 'NET',
}

/**
 * Schema for SaleProceedsType
 */
export const saleProceedsTypeSchema: Schema<SaleProceedsType> = stringEnum(
  SaleProceedsType,
  true
);
