/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleTermType
 */
export enum SaleTermType {
  Long = 'LONG',
  Short = 'SHORT',
}

/**
 * Schema for SaleTermType
 */
export const saleTermTypeSchema: Schema<SaleTermType> = stringEnum(
  SaleTermType,
  true
);
