/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Secured
 */
export enum Secured {
  Covered = 'COVERED',
  Naked = 'NAKED',
}

/**
 * Schema for Secured
 */
export const securedSchema: Schema<Secured> = stringEnum(Secured, true);
