/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecurityType
 */
export enum SecurityType {
  Stock = 'STOCK',
  Mutualfund = 'MUTUALFUND',
  Debt = 'DEBT',
  Option = 'OPTION',
  Sweep = 'SWEEP',
  Other = 'OTHER',
  Bond = 'BOND',
}

/**
 * Schema for SecurityType
 */
export const securityTypeSchema: Schema<SecurityType> = stringEnum(
  SecurityType,
  true
);
