/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecurityIdType
 */
export enum SecurityIdType {
  Cusip = 'CUSIP',
  Isin = 'ISIN',
  Sedol = 'SEDOL',
  Sicc = 'SICC',
  Valor = 'VALOR',
  Wkn = 'WKN',
}

/**
 * Schema for SecurityIdType
 */
export const securityIdTypeSchema: Schema<SecurityIdType> = stringEnum(
  SecurityIdType,
  true
);
