/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Amount of state income tax withheld */
export interface StateTaxWithholding {
  /** Amount of state income tax withheld */
  taxWithheld?: number;
  /** Filer's state tax id */
  taxId?: string;
  /** Income amount for state tax purposes */
  income?: number;
  additionalProperties?: Record<string, unknown>;
}

export const stateTaxWithholdingSchema: Schema<StateTaxWithholding> = typedExpandoObject(
  {
    taxWithheld: ['taxWithheld', optional(number())],
    taxId: ['taxId', optional(string())],
    income: ['income', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
