/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { StockType, stockTypeSchema } from './stockType';

/** Information about the stock security specific to the type of security */
export interface StockSecurityEntity {
  /** Units in the FI's street name, positive quantity */
  unitsStreet?: number;
  /** Units in user's name directly, positive  quantity */
  unitsUser?: number;
  /** Reinvest dividends */
  reinvestDividends?: boolean;
  stockType?: StockType;
  /** Current yield */
  yield?: number;
  /** Yield as-of date */
  yieldAsOfDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const stockSecurityEntitySchema: Schema<StockSecurityEntity> = typedExpandoObject(
  {
    unitsStreet: ['unitsStreet', optional(number())],
    unitsUser: ['unitsUser', optional(number())],
    reinvestDividends: ['reinvestDividends', optional(boolean())],
    stockType: ['stockType', optional(stockTypeSchema)],
    yield: ['yield', optional(number())],
    yieldAsOfDate: ['yieldAsOfDate', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
