/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StockType
 */
export enum StockType {
  Bond = 'BOND',
  Debt = 'DEBT',
  Mutualfund = 'MUTUALFUND',
  Option = 'OPTION',
  Other = 'OTHER',
  Stock = 'STOCK',
  Sweep = 'SWEEP',
}

/**
 * Schema for StockType
 */
export const stockTypeSchema: Schema<StockType> = stringEnum(StockType, true);
