/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubAccountFund
 */
export enum SubAccountFund {
  Cash = 'CASH',
  Margin = 'MARGIN',
  Short = 'SHORT',
  Others = 'OTHERS',
}

/**
 * Schema for SubAccountFund
 */
export const subAccountFundSchema: Schema<SubAccountFund> = stringEnum(
  SubAccountFund,
  true
);
