/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubAccount
 */
export enum SubAccount {
  Cash = 'CASH',
  Margin = 'MARGIN',
  Short = 'SHORT',
  Other = 'OTHER',
}

/**
 * Schema for SubAccount
 */
export const subAccountSchema: Schema<SubAccount> = stringEnum(
  SubAccount,
  true
);
