/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubAccountSecurityType
 */
export enum SubAccountSecurityType {
  Cash = 'CASH',
  Margin = 'MARGIN',
  Short = 'SHORT',
  Others = 'OTHERS',
}

/**
 * Schema for SubAccountSecurityType
 */
export const subAccountSecurityTypeSchema: Schema<SubAccountSecurityType> = stringEnum(
  SubAccountSecurityType,
  true
);
