/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Information about the sweep security specific to the type of security */
export interface SweepSecurityEntity {
  /** Balance of funds in account */
  currentBalance?: number;
  /** Balance of funds available for use */
  availableBalance?: number;
  /** As-of date of balances */
  balanceAsOf?: string;
  /** Whether or not checks can be written on the account */
  checks?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const sweepSecurityEntitySchema: Schema<SweepSecurityEntity> = typedExpandoObject(
  {
    currentBalance: ['currentBalance', optional(number())],
    availableBalance: ['availableBalance', optional(number())],
    balanceAsOf: ['balanceAsOf', optional(string())],
    checks: ['checks', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
