/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  BusinessIncomeStatement,
  businessIncomeStatementSchema,
} from './businessIncomeStatement';
import {
  CryptocurrencyTaxStatementList,
  cryptocurrencyTaxStatementListSchema,
} from './cryptocurrencyTaxStatementList';
import {
  FarmIncomeStatement,
  farmIncomeStatementSchema,
} from './farmIncomeStatement';
import {
  FarmRentalIncomeStatement,
  farmRentalIncomeStatementSchema,
} from './farmRentalIncomeStatement';
import { Form1041K1, form1041K1Schema } from './form1041K1';
import { Form1042S, form1042SSchema } from './form1042S';
import { Form1065K1, form1065K1Schema } from './form1065K1';
import { Form1095A, form1095ASchema } from './form1095A';
import { Form1095B, form1095BSchema } from './form1095B';
import { Form1095C, form1095CSchema } from './form1095C';
import { Form1097Btc, form1097BtcSchema } from './form1097Btc';
import { Form1098, form1098Schema } from './form1098';
import { Form1098C, form1098CSchema } from './form1098C';
import { Form1098E, form1098ESchema } from './form1098E';
import { Form1098Ma, form1098MaSchema } from './form1098Ma';
import { Form1098Q, form1098QSchema } from './form1098Q';
import { Form1098T, form1098TSchema } from './form1098T';
import { Form1099A, form1099ASchema } from './form1099A';
import { Form1099B, form1099BSchema } from './form1099B';
import { Form1099C, form1099CSchema } from './form1099C';
import { Form1099Cap, form1099CapSchema } from './form1099Cap';
import {
  Form1099ConsolidatedStatement,
  form1099ConsolidatedStatementSchema,
} from './form1099ConsolidatedStatement';
import { Form1099Div, form1099DivSchema } from './form1099Div';
import { Form1099G, form1099GSchema } from './form1099G';
import { Form1099H, form1099HSchema } from './form1099H';
import { Form1099Int, form1099IntSchema } from './form1099Int';
import { Form1099K, form1099KSchema } from './form1099K';
import { Form1099Ls, form1099LsSchema } from './form1099Ls';
import { Form1099Ltc, form1099LtcSchema } from './form1099Ltc';
import { Form1099Misc, form1099MiscSchema } from './form1099Misc';
import { Form1099Nec, form1099NecSchema } from './form1099Nec';
import { Form1099Oid, form1099OidSchema } from './form1099Oid';
import { Form1099Patr, form1099PatrSchema } from './form1099Patr';
import { Form1099Q, form1099QSchema } from './form1099Q';
import { Form1099Qa, form1099QaSchema } from './form1099Qa';
import { Form1099R, form1099RSchema } from './form1099R';
import { Form1099S, form1099SSchema } from './form1099S';
import { Form1099Sa, form1099SaSchema } from './form1099Sa';
import { Form1099Sb, form1099SbSchema } from './form1099Sb';
import { Form1120SK1, form1120Sk1Schema } from './form1120Sk1';
import { Form2439, form2439Schema } from './form2439';
import { Form3921, form3921Schema } from './form3921';
import { Form3922, form3922Schema } from './form3922';
import { Form5498, form5498Schema } from './form5498';
import { Form5498Esa, form5498EsaSchema } from './form5498Esa';
import { Form5498Qa, form5498QaSchema } from './form5498Qa';
import { Form5498Sa, form5498SaSchema } from './form5498Sa';
import { FormW2, formW2Schema } from './formW2';
import { FormW2C, formW2CSchema } from './formW2C';
import { FormW2G, formW2GSchema } from './formW2G';
import {
  RentalIncomeStatement,
  rentalIncomeStatementSchema,
} from './rentalIncomeStatement';
import {
  RoyaltyIncomeStatement,
  royaltyIncomeStatementSchema,
} from './royaltyIncomeStatement';
import {
  TaxRefundDirectDeposit,
  taxRefundDirectDepositSchema,
} from './taxRefundDirectDeposit';

/** Tax data container for API requests and responses */
export interface TaxData {
  /** Business Income Statement for IRS Form 1040 Schedule C */
  businessIncomeStatement?: BusinessIncomeStatement;
  /** Cryptocurrency Tax Statement list */
  cryptocurrencyTaxStatement?: CryptocurrencyTaxStatementList;
  /** Farm Income Statement for IRS Form 1040 Schedule F */
  farmIncomeStatement?: FarmIncomeStatement;
  /** Farm Rental Income Statement for IRS Form 4835 */
  farmRentalIncomeStatement?: FarmRentalIncomeStatement;
  /** Rental Income Statement for IRS Form 1040 Schedule E */
  rentalIncomeStatement?: RentalIncomeStatement;
  /** Royalty Income Statement for IRS Form 1040 Schedule E */
  royaltyIncomeStatement?: RoyaltyIncomeStatement;
  /** Beneficiary's Share of Income, Deductions, Credits, etc. */
  tax1041K1?: Form1041K1;
  /** Foreign Person's U.S. Source Income Subject to Withholding */
  tax1042S?: Form1042S;
  /** Partner's Share of Income, Deductions, Credits, etc. */
  tax1065K1?: Form1065K1;
  /** Health Insurance Marketplace Statement */
  tax1095A?: Form1095A;
  /** Health Coverage */
  tax1095B?: Form1095B;
  /** Employer-Provided Health Insurance Offer and Coverage */
  tax1095C?: Form1095C;
  /** Bond Tax Credit */
  tax1097Btc?: Form1097Btc;
  /** Mortgage Interest Statement */
  tax1098?: Form1098;
  /** Contributions of Motor Vehicles, Boats, and Airplanes */
  tax1098C?: Form1098C;
  /** Student Loan Interest Statement */
  tax1098E?: Form1098E;
  /** Mortgage Assistance Payments */
  tax1098Ma?: Form1098Ma;
  /** Qualifying Longevity Annuity Contract Information */
  tax1098Q?: Form1098Q;
  /** Tuition Statement */
  tax1098T?: Form1098T;
  /** Acquisition or Abandonment of Secured Property */
  tax1099A?: Form1099A;
  /** Proceeds From Broker and Barter Exchange Transactions */
  tax1099B?: Form1099B;
  /** Cancellation of Debt */
  tax1099C?: Form1099C;
  /** Changes in Corporate Control and Capital Structure */
  tax1099Cap?: Form1099Cap;
  /** Consolidated Statement for combined IRS Form 1099s */
  tax1099ConsolidatedStatement?: Form1099ConsolidatedStatement;
  /** Dividends and Distributions */
  tax1099Div?: Form1099Div;
  /** Certain Government Payments */
  tax1099G?: Form1099G;
  /** Health Coverage Tax Credit (HCTC) Advance Payments */
  tax1099H?: Form1099H;
  /** Interest Income */
  tax1099Int?: Form1099Int;
  /** Merchant Card and Third-Party Network Payments */
  tax1099K?: Form1099K;
  /** Reportable Life Insurance Sale */
  tax1099Ls?: Form1099Ls;
  /** Long-Term Care and Accelerated Death Benefits */
  tax1099Ltc?: Form1099Ltc;
  /** Miscellaneous Income */
  tax1099Misc?: Form1099Misc;
  /** Non-Employee Compensation */
  tax1099Nec?: Form1099Nec;
  /** Original Issue Discount */
  tax1099Oid?: Form1099Oid;
  /** Taxable Distributions Received From Cooperatives */
  tax1099Patr?: Form1099Patr;
  /** Payments From Qualified Education Programs */
  tax1099Q?: Form1099Q;
  /** Distributions From ABLE Accounts */
  tax1099Qa?: Form1099Qa;
  /** Distributions from Pensions, Annuities, Retirement or Profit-Sharing Plans, IRAs, Insurance Contracts, etc. */
  tax1099R?: Form1099R;
  /** Proceeds From Real Estate Transactions */
  tax1099S?: Form1099S;
  /** Distributions From an HSA, Archer MSA, or Medicare Advantage MSA */
  tax1099Sa?: Form1099Sa;
  /** Seller's Investment in Life Insurance Contract */
  tax1099Sb?: Form1099Sb;
  /** Shareholder's Share of Income, Deductions, Credits, etc. */
  tax1120Sk1?: Form1120SK1;
  /** Notice to Shareholder of Undistributed Long-Term Capital Gains */
  tax2439?: Form2439;
  /** Exercise of an Incentive Stock Option Under Section 422(b) */
  tax3921?: Form3921;
  /** Transfer of Stock Acquired Through an Employee Stock Purchase Plan under Section 423(c) */
  tax3922?: Form3922;
  /** Split-Interest Trust Beneficiary's schedule K-1 */
  tax5227K1?: Form1041K1;
  /** IRA Contribution Information */
  tax5498?: Form5498;
  /** Coverdell ESA Contribution Information */
  tax5498Esa?: Form5498Esa;
  /** ABLE Account Contribution Information */
  tax5498Qa?: Form5498Qa;
  /** HSA, Archer MSA, or Medicare Advantage (MA) MSA Information */
  tax5498Sa?: Form5498Sa;
  /** Wage and Tax Statement */
  taxW2?: FormW2;
  /** IRS form W-2c, Corrected Wage and Tax Statement */
  taxW2C?: FormW2C;
  /** Certain Gambling Winnings */
  taxW2G?: FormW2G;
  /** Tax refund direct deposit information */
  taxRefundDirectDeposit?: TaxRefundDirectDeposit;
  additionalProperties?: Record<string, unknown>;
}

export const taxDataSchema: Schema<TaxData> = typedExpandoObject(
  {
    businessIncomeStatement: [
      'businessIncomeStatement',
      optional(lazy(() => businessIncomeStatementSchema)),
    ],
    cryptocurrencyTaxStatement: [
      'cryptocurrencyTaxStatement',
      optional(lazy(() => cryptocurrencyTaxStatementListSchema)),
    ],
    farmIncomeStatement: [
      'farmIncomeStatement',
      optional(lazy(() => farmIncomeStatementSchema)),
    ],
    farmRentalIncomeStatement: [
      'farmRentalIncomeStatement',
      optional(lazy(() => farmRentalIncomeStatementSchema)),
    ],
    rentalIncomeStatement: [
      'rentalIncomeStatement',
      optional(lazy(() => rentalIncomeStatementSchema)),
    ],
    royaltyIncomeStatement: [
      'royaltyIncomeStatement',
      optional(lazy(() => royaltyIncomeStatementSchema)),
    ],
    tax1041K1: ['tax1041K1', optional(lazy(() => form1041K1Schema))],
    tax1042S: ['tax1042S', optional(lazy(() => form1042SSchema))],
    tax1065K1: ['tax1065K1', optional(lazy(() => form1065K1Schema))],
    tax1095A: ['tax1095A', optional(lazy(() => form1095ASchema))],
    tax1095B: ['tax1095B', optional(lazy(() => form1095BSchema))],
    tax1095C: ['tax1095C', optional(lazy(() => form1095CSchema))],
    tax1097Btc: ['tax1097Btc', optional(lazy(() => form1097BtcSchema))],
    tax1098: ['tax1098', optional(lazy(() => form1098Schema))],
    tax1098C: ['tax1098C', optional(lazy(() => form1098CSchema))],
    tax1098E: ['tax1098E', optional(lazy(() => form1098ESchema))],
    tax1098Ma: ['tax1098Ma', optional(lazy(() => form1098MaSchema))],
    tax1098Q: ['tax1098Q', optional(lazy(() => form1098QSchema))],
    tax1098T: ['tax1098T', optional(lazy(() => form1098TSchema))],
    tax1099A: ['tax1099A', optional(lazy(() => form1099ASchema))],
    tax1099B: ['tax1099B', optional(lazy(() => form1099BSchema))],
    tax1099C: ['tax1099C', optional(lazy(() => form1099CSchema))],
    tax1099Cap: ['tax1099Cap', optional(lazy(() => form1099CapSchema))],
    tax1099ConsolidatedStatement: [
      'tax1099ConsolidatedStatement',
      optional(lazy(() => form1099ConsolidatedStatementSchema)),
    ],
    tax1099Div: ['tax1099Div', optional(lazy(() => form1099DivSchema))],
    tax1099G: ['tax1099G', optional(lazy(() => form1099GSchema))],
    tax1099H: ['tax1099H', optional(lazy(() => form1099HSchema))],
    tax1099Int: ['tax1099Int', optional(lazy(() => form1099IntSchema))],
    tax1099K: ['tax1099K', optional(lazy(() => form1099KSchema))],
    tax1099Ls: ['tax1099Ls', optional(lazy(() => form1099LsSchema))],
    tax1099Ltc: ['tax1099Ltc', optional(lazy(() => form1099LtcSchema))],
    tax1099Misc: ['tax1099Misc', optional(lazy(() => form1099MiscSchema))],
    tax1099Nec: ['tax1099Nec', optional(lazy(() => form1099NecSchema))],
    tax1099Oid: ['tax1099Oid', optional(lazy(() => form1099OidSchema))],
    tax1099Patr: ['tax1099Patr', optional(lazy(() => form1099PatrSchema))],
    tax1099Q: ['tax1099Q', optional(lazy(() => form1099QSchema))],
    tax1099Qa: ['tax1099Qa', optional(lazy(() => form1099QaSchema))],
    tax1099R: ['tax1099R', optional(lazy(() => form1099RSchema))],
    tax1099S: ['tax1099S', optional(lazy(() => form1099SSchema))],
    tax1099Sa: ['tax1099Sa', optional(lazy(() => form1099SaSchema))],
    tax1099Sb: ['tax1099Sb', optional(lazy(() => form1099SbSchema))],
    tax1120Sk1: ['tax1120SK1', optional(lazy(() => form1120Sk1Schema))],
    tax2439: ['tax2439', optional(lazy(() => form2439Schema))],
    tax3921: ['tax3921', optional(lazy(() => form3921Schema))],
    tax3922: ['tax3922', optional(lazy(() => form3922Schema))],
    tax5227K1: ['tax5227K1', optional(lazy(() => form1041K1Schema))],
    tax5498: ['tax5498', optional(lazy(() => form5498Schema))],
    tax5498Esa: ['tax5498Esa', optional(lazy(() => form5498EsaSchema))],
    tax5498Qa: ['tax5498Qa', optional(lazy(() => form5498QaSchema))],
    tax5498Sa: ['tax5498Sa', optional(lazy(() => form5498SaSchema))],
    taxW2: ['taxW2', optional(lazy(() => formW2Schema))],
    taxW2C: ['taxW2C', optional(lazy(() => formW2CSchema))],
    taxW2G: ['taxW2G', optional(lazy(() => formW2GSchema))],
    taxRefundDirectDeposit: [
      'taxRefundDirectDeposit',
      optional(lazy(() => taxRefundDirectDepositSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
