/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** An additional tax form attribute for use when a defined field is not available */
export interface TaxFormAttribute {
  /** Name of attribute */
  name?: string;
  /** Value of attribute */
  value?: string;
  /** Box number on a tax form, if any */
  boxNumber?: string;
  /** Tax form code for the given box number, if any */
  code?: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxFormAttributeSchema: Schema<TaxFormAttribute> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    value: ['value', optional(string())],
    boxNumber: ['boxNumber', optional(string())],
    code: ['code', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
