/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxPartyType
 */
export enum TaxPartyType {
  Business = 'BUSINESS',
  Individual = 'INDIVIDUAL',
}

/**
 * Schema for TaxPartyType
 */
export const taxPartyTypeSchema: Schema<TaxPartyType> = stringEnum(
  TaxPartyType,
  true
);
