/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Address, addressSchema } from './address';
import { BusinessName, businessNameSchema } from './businessName';
import { IndividualName, individualNameSchema } from './individualName';
import { TaxPartyType, taxPartyTypeSchema } from './taxPartyType';
import {
  TelephoneNumberPlusExtension,
  telephoneNumberPlusExtensionSchema,
} from './telephoneNumberPlusExtension';

/** Legal entity for issuer or recipient, used across all tax forms */
export interface TaxParty {
  /** Issuer or recipient Tax Identification Number. Usually EIN for issuer and SSN for recipient */
  tin?: string;
  /** Type of issuer or recipient legal entity, as "BUSINESS" or "INDIVIDUAL". Commonly BUSINESS for issuer and INDIVIDUAL for recipient */
  partyType?: TaxPartyType;
  /** Individual issuer or recipient name */
  individualName?: IndividualName;
  /** Business issuer or recipient name */
  businessName?: BusinessName;
  /** Issuer or recipient address */
  address?: Address;
  /** Issuer or recipient telephone number */
  phone?: TelephoneNumberPlusExtension;
  /** Issuer or recipient email address. (Additional information, not part of IRS forms) */
  email?: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxPartySchema: Schema<TaxParty> = typedExpandoObject(
  {
    tin: ['tin', optional(string())],
    partyType: ['partyType', optional(taxPartyTypeSchema)],
    individualName: [
      'individualName',
      optional(lazy(() => individualNameSchema)),
    ],
    businessName: ['businessName', optional(lazy(() => businessNameSchema))],
    address: ['address', optional(lazy(() => addressSchema))],
    phone: ['phone', optional(lazy(() => telephoneNumberPlusExtensionSchema))],
    email: ['email', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
