/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** IRS Form 8888 Direct Deposit Information */
export interface TaxRefundDirectDeposit {
  /** Name of institution */
  institutionName?: string;
  /** Routing transit number */
  rtn?: string;
  /** Account number */
  accountNumber?: string;
  /** Account nickname */
  accountNickName?: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxRefundDirectDepositSchema: Schema<TaxRefundDirectDeposit> = typedExpandoObject(
  {
    institutionName: ['institutionName', optional(string())],
    rtn: ['rtn', optional(string())],
    accountNumber: ['accountNumber', optional(string())],
    accountNickName: ['accountNickName', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
