/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { TaxStatement, taxStatementSchema } from './taxStatement';

/** Tax statement list containing one or more tax statements */
export interface TaxStatementList {
  /** The list of tax statements */
  statements?: TaxStatement[];
  additionalProperties?: Record<string, unknown>;
}

export const taxStatementListSchema: Schema<TaxStatementList> = typedExpandoObject(
  {
    statements: ['statements', optional(array(lazy(() => taxStatementSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
