/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TelephoneNumberType
 */
export enum TelephoneNumberType {
  Business = 'BUSINESS',
  Cell = 'CELL',
  Fax = 'FAX',
  Home = 'HOME',
}

/**
 * Schema for TelephoneNumberType
 */
export const telephoneNumberTypeSchema: Schema<TelephoneNumberType> = stringEnum(
  TelephoneNumberType,
  true
);
