/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  Iso3166CountryCode,
  iso3166CountryCodeSchema,
} from './iso3166CountryCode';
import {
  TelephoneNumberType,
  telephoneNumberTypeSchema,
} from './telephoneNumberType';

/** Standard for international phone numbers */
export interface TelephoneNumber {
  /** Type of phone number: HOME, BUSINESS, CELL, FAX */
  type?: TelephoneNumberType;
  /** Country calling codes defined by ITU-T recommendations E.123 and E.164 */
  country?: Iso3166CountryCode;
  /** Telephone subscriber number defined by ITU-T recommendation E.164 */
  number?: string;
  additionalProperties?: Record<string, unknown>;
}

export const telephoneNumberSchema: Schema<TelephoneNumber> = typedExpandoObject(
  {
    type: ['type', optional(telephoneNumberTypeSchema)],
    country: ['country', optional(iso3166CountryCodeSchema)],
    number: ['number', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
