/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionReason
 */
export enum TransactionReason {
  Call = 'CALL',
  Sell = 'SELL',
  Maturity = 'MATURITY',
}

/**
 * Schema for TransactionReason
 */
export const transactionReasonSchema: Schema<TransactionReason> = stringEnum(
  TransactionReason,
  true
);
