/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  TransactionsEntityTransactions,
  transactionsEntityTransactionsSchema,
} from './containers/transactionsEntityTransactions';
import { Links, linksSchema } from './links';

/** Optionally paginated array of transactions */
export interface TransactionsEntity {
  links?: Links;
  /** An array of transactions with entity types dependent on the account type (deposit, investment, loan, or line of credit) */
  transactions?: TransactionsEntityTransactions[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionsEntitySchema: Schema<TransactionsEntity> = typedExpandoObject(
  {
    links: ['links', optional(lazy(() => linksSchema))],
    transactions: [
      'transactions',
      optional(array(transactionsEntityTransactionsSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
