/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransferAction
 */
export enum TransferAction {
  In = 'IN',
  Out = 'OUT',
}

/**
 * Schema for TransferAction
 */
export const transferActionSchema: Schema<TransferAction> = stringEnum(
  TransferAction,
  true
);
