/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransationStatus
 */
export enum TransationStatus {
  Pending = 'PENDING',
  Memo = 'MEMO',
  Posted = 'POSTED',
  Authorization = 'AUTHORIZATION',
}

/**
 * Schema for TransationStatus
 */
export const transationStatusSchema: Schema<TransationStatus> = stringEnum(
  TransationStatus,
  true
);
