/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeFormType
 */
export enum TypeFormType {
  BusinessIncomeStatement = 'BusinessIncomeStatement',
  CryptocurrencyTaxStatement = 'CryptocurrencyTaxStatement',
  FarmIncomeStatement = 'FarmIncomeStatement',
  FarmRentalIncomeStatement = 'FarmRentalIncomeStatement',
  RentalIncomeStatement = 'RentalIncomeStatement',
  RoyaltyIncomeStatement = 'RoyaltyIncomeStatement',
  Tax1041K1 = 'Tax1041K1',
  Tax1042S = 'Tax1042S',
  Tax1065K1 = 'Tax1065K1',
  Tax1095A = 'Tax1095A',
  Tax1095B = 'Tax1095B',
  Tax1095C = 'Tax1095C',
  Tax1097Btc = 'Tax1097Btc',
  Tax1098 = 'Tax1098',
  Tax1098C = 'Tax1098C',
  Tax1098E = 'Tax1098E',
  Tax1098Ma = 'Tax1098Ma',
  Tax1098Q = 'Tax1098Q',
  Tax1098T = 'Tax1098T',
  Tax1099A = 'Tax1099A',
  Tax1099B = 'Tax1099B',
  Tax1099C = 'Tax1099C',
  Tax1099Cap = 'Tax1099Cap',
  Tax1099ConsolidatedStatement = 'Tax1099ConsolidatedStatement',
  Tax1099Div = 'Tax1099Div',
  Tax1099G = 'Tax1099G',
  Tax1099H = 'Tax1099H',
  Tax1099Int = 'Tax1099Int',
  Tax1099K = 'Tax1099K',
  Tax1099Ls = 'Tax1099Ls',
  Tax1099Ltc = 'Tax1099Ltc',
  Tax1099Misc = 'Tax1099Misc',
  Tax1099Nec = 'Tax1099Nec',
  Tax1099Oid = 'Tax1099Oid',
  Tax1099Patr = 'Tax1099Patr',
  Tax1099Q = 'Tax1099Q',
  Tax1099Qa = 'Tax1099Qa',
  Tax1099R = 'Tax1099R',
  Tax1099S = 'Tax1099S',
  Tax1099Sa = 'Tax1099Sa',
  Tax1099Sb = 'Tax1099Sb',
  Tax1120Sk1 = 'Tax1120SK1',
  Tax2439 = 'Tax2439',
  Tax3921 = 'Tax3921',
  Tax3922 = 'Tax3922',
  Tax5227K1 = 'Tax5227K1',
  Tax5498 = 'Tax5498',
  Tax5498Esa = 'Tax5498Esa',
  Tax5498Qa = 'Tax5498Qa',
  Tax5498Sa = 'Tax5498Sa',
  TaxW2 = 'TaxW2',
  TaxW2C = 'TaxW2C',
  TaxW2G = 'TaxW2G',
}

/**
 * Schema for TypeFormType
 */
export const typeFormTypeSchema: Schema<TypeFormType> = stringEnum(
  TypeFormType,
  true
);
