/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeDataType
 */
export enum TypeDataType {
  Base64Pdf = 'BASE64_PDF',
  Json = 'JSON',
}

/**
 * Schema for TypeDataType
 */
export const typeDataTypeSchema: Schema<TypeDataType> = stringEnum(
  TypeDataType,
  true
);
