/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnitType
 */
export enum UnitType {
  Currency = 'CURRENCY',
  Shares = 'SHARES',
}

/**
 * Schema for UnitType
 */
export const unitTypeSchema: Schema<UnitType> = stringEnum(UnitType, true);
