/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Version
 */
export enum Version {
  V2 = 'v2',
}

/**
 * Schema for Version
 */
export const versionSchema: Schema<Version> = stringEnum(Version, true);
