/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface Vesting {
  /** Vested quantity (Vested shares total qty of vesting tranche) */
  vestedQuantity?: number;
  /** Vested balance at grant (aggregate of all vestings) */
  vestedValue?: number;
  vestingDate?: string;
  vestExpireDate?: string;
  vestedStatus?: string;
  additionalProperties?: Record<string, unknown>;
}

export const vestingSchema: Schema<Vesting> = typedExpandoObject(
  {
    vestedQuantity: ['vestedQuantity', optional(number())],
    vestedValue: ['vestedValue', optional(number())],
    vestingDate: ['vestingDate', optional(string())],
    vestExpireDate: ['vestExpireDate', optional(string())],
    vestedStatus: ['vestedStatus', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
